### ISSUE TITLE
XML-RPC support for blog publishing

### ISSUE THREAD

**Issue by szelpe** [mike-ward/Markdown-Edit#10]
I really like **Markdown Edit** so far, I'm considering it as my main editor for my blog. It'd be really nice if I could directly publish my files to wordpress from the editor.

There is already a .NET implementation of the wordpress XML RPC API:

[WordPressSharp](https://github.com/abrudtkuhl/WordPressSharp)

Since I'm a .NET developer myself, I'd like to help implementing this feature, if you agree.

What do you think?

**Comment by mike-ward** [comment]
This sounds like something that might better be expressed as an extension. I don't have any extension points in the editor at the moment but that should be easy if we use something like MEF. The bigger question is how would it work in practice?

- Settings need to be stored
- Images have to be uploaded and mapped to the content
- An interface for publishing will likely have to be added
- Enumerating and downloading articles
- Temporary storage for images when downloaded

Don't get me wrong. It's an interesting idea. It's also a big project, on par with the whole fo the rest of the project.

It might be good to start off with some use cases so there's some agreement on what this feature might look like.

**Comment by mike-ward** [comment]
Would a Dropbox to Wordpress plug in work for you? Edit your files locally and they publish automatically.

https://wordpress.org/plugins/post-via-dropbox/

**Comment by szelpe** [comment]
My vision is something similar to Word as a blogging tool: [Word 2013 Publish to Blogs](http://anewdomain.net/2014/01/29/microsoft-word-2013-blogging-simple/)

You can register Blog Accounts, open existing posts or create a new one and a publish command which updates the post on the blog.

But, I'd rather do it in an incremental way, starting with a small MVP. An obvious first step could be a publish command which can publish the currently opened document to the blog as a new post.

Btw, are you planning a plugin system with MEF? That sounds nice, just have to think on the extensibility points.

Post via dropbox, or another service like IFTTT is a nice workaround too, but not ideal :) .

**Comment by mike-ward** [comment]
I wasn't planning on doing MEF, but then I wasn't planning on blog publishing either. However, if this were to be done, then I think a mechanism that supports more than WordPress is needed. 

Likely that means some type of a blog/publish manager and registration process/information.

**Comment by szelpe** [comment]
There is a nice Markdown editor which supports publishing, but doesn't seem to be able to load an already existing blogpost:

https://stackedit.io/

**Comment by mike-ward** [comment]
It's a slick setup but as you can see, there's quite a bit of extra UI to support credentials, etc.

The issue as I see it is do I want Markdown Edit to become a Windows Live Writer like application. That's a considerably complicated undertaking. In addition to the blog credentials, MDE will have to deal storing images locally and possibly downloading the blog template to get an accurate rendering.

The more I we talk about this the more I think this is outside the scope of the project. I'm avoiding making Markdown Edit a publishing platform because the complexity of the interfaces.

**Comment by mike-ward** [comment]
Checkout https://github.com/robmen/tinypost

It might be possible to build a separate app that handles posting generically. MDE could shell out to it or something.

**Comment by szelpe** [comment]
ok, that's a fair point, thanks.

**Comment by mike-ward** [comment]
MarkPad has a reasonable interface for blog posting. Have a look. I could see something like that working.

**Comment by szelpe** [comment]
Yeah, MarkPad is impressive indeed, thanks.
