### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by mikjsmith** [mike-ward/Markdown-Edit#103]
Is it possible to have a portable version that runs straight from a USB? Can the dotnet libraries be a part of that??

**Comment by mike-ward** [comment]
Not at this time.

**Comment by shnbwmn** [comment]
Another vote here for a portable version.

**Comment by ali4ever4** [comment]
+1

**Comment by RoyiAvital** [comment]
Portable version would be a game changer.
Exactly as @shnbwmn explained.

Could you please reconsider it?
We don't need the Dot Net Libraries, just EXE which uses the local folder for settings.

Thank You.

**Comment by mike-ward** [comment]
OK, here's my proposal.

Add a command line switch `-p [path]`. When path is not specified it defaults to to `[application folder]\app_data`. Settings/templates, etc. are then read /written from the alternate location.

**Comment by mikjsmith** [comment]
Good solution that doesnt overcomplicate things

**Comment by RoyiAvital** [comment]
@mike-ward, I didn't understand.

Let's say I'm downloading the latest version.
I extract the MSI into a USB in a folder under the name MarkDownEdit.

What should I do from there?

**Comment by mikjsmith** [comment]
You need to start MDE from the command line with a switch and directory path which will store the settings. Might be worth distributing as a ZIP rather than an EXE but whatever is easiest for Mike.

**Comment by RoyiAvital** [comment]
@mikjsmith , Will it work on current version or only in the next ones?

Namely, will it work on the current 1.26 version?

**Comment by mikjsmith** [comment]
I think thats a feature to add....

**Comment by RoyiAvital** [comment]
I see.
So I hope it will be delivered in a ZIP with .bat file wrapper for portable mode.

Thank You.

**Comment by mike-ward** [comment]
Thinking about this more, maybe I can assume "portable" mode when the application is launched from other that `<user>/App_Data/local/Markdown Edit` Eliminates the switch and wrapper files.

**Comment by mikjsmith** [comment]
Elegant solution

**Comment by RoyiAvital** [comment]
Perfect!

@mike-ward , When can we try it?

Thank You.

**Comment by mike-ward** [comment]
Whoa! You want me to actually implement it ? :sunglasses:

**Comment by RoyiAvital** [comment]
@mike-ward ,
I wish I new to program.
I'm limited to MATLAB :smile: .

I meant to test a build with the feature (If you intend to create a test build before release).

I'm so excited to finally have a decent MarkDown (CommonMark) editor locally on Windows.
It almost made me move to OS X (Very bad move).

Thank You.

**Comment by shnbwmn** [comment]
Oh, it's nice to see the wheel rolling!  The last proposal sounds good (use from different dir). Ordinary end users won't know what command-line switches are or how to use them.

**Comment by mike-ward** [comment]
OK, here's a crack at a portable version:

https://temp-share.com/f/rwktjigair

This will write files into a folder called AppData in the mde.exe folder.

Some settings will still be saved to the target system using .NET's isolated storage mechanism (last window position for instance).

**Comment by RoyiAvital** [comment]
Great!
I will be downloading and test.

By the way, any way to reset this "Isolated Storage"n manually?
Anyway to overcome it in the software itself?

Thank You.

**Comment by mikjsmith** [comment]
First run through on my Win10x64 machine shows this working as expected with en_GB spelling library. Nothing obviously not working :)

**Comment by mike-ward** [comment]
@RoyiAvital It depends on the goals and expected functionality.

If the goal to make it fully portable, that may never happen considering the .NET platform is required in some form.

If the goal is to never write to the target system, that's doable by simply not saving the settings. But that begs the question as to what we're trying to accomplish here. Are we trying to make it never write the target system, or are we trying to make the program easy to use in a portable fashion?

Remembering the last window position and last open file are nice-to-haves IMO. But they're also system specific. So saving them anywhere other than the target system is a tough sell for me. I'm open to options, let's discuss.

**Comment by RoyiAvital** [comment]
@mike-ward ,
Many people now share and sync their programs between many computers.

For me, I'd like of have the same experience from a program anywhere I run it.
Today, besides Office and MATLAB all the programs I use are from [PortableApps](http://portableapps.com/).

For me, it is the best way to go.
Moreover, being able to reset the program whenever I want is a feature, the way I see it.

The one thing I miss is MarkDown editor.
for now I use StackEdit, as it is as portable as it gets.
Yet It's hard to work with with GIT.

I appreciate your openness on the issue.

Thank You.

**Comment by mikjsmith** [comment]
Easy to use in a portable fashion - I guess there are settings that will be potentially device specific.

I dont know much about .Net, so this (http://developer.telerik.com/featured/the-era-of-portable-net/) may be irrelevant, but his quote struck me...

"Can I build a .NET app on one Windows machine and run it seamlessly on another Windows machine, without having to install or configure anything on the second machine? The answer is an emphatic “yes.”"

**Comment by mike-ward** [comment]
> http://developer.telerik.com/featured/the-era-of-portable-net/

This is a future .NET where the runtime is a package distributed with the application. It's not clear to me if they're going to support legacy desktop apps like MDE however. The current focus appears to be on ASP.NET and server-side applications.

**Comment by shnbwmn** [comment]
Tested on Win 10 x64, and it does indeed work as specified.

With regards to recently opened docs: perhaps the doc paths could be saved as relative rather than absolute (if that's possible?), and the user.config folder moved to the app folder on exit. This makes sense when, for instance, the user's files are on the same drive as the program.

**Comment by mike-ward** [comment]
Relative paths only work if you're on the same drive. I'm not convinced there's a reason to use relative paths.

If the goal is to leave no trace on the system, it simply can't happen. Windows records all sorts stuff about applications when they run. The portable apps website makes a point of this as well.

If the goal is to provide a low impact, no-install way to run MDE, then I think we are there.

As to the .NET runtime, there is no solution at this time. .NET 4.5.2 (or later) must be installed on the target system for MDE to work.

**Comment by shnbwmn** [comment]
Well, then it's settled I guess :) Thank you very much for taking the time to do this. If you don't mind, I'll happily post this as a [submission to Portable Freeware](http://www.portablefreeware.com/forums/viewforum.php?f=4) when the .zip version is released.

**Comment by mike-ward** [comment]
OK, future releases will include a .zip build. I'll update the wiki about the portable feature.

**Comment by RoyiAvital** [comment]
@mike-ward , Is there a way to reset those .NET settings you mentioned earlier?

Thank You.

**Comment by mike-ward** [comment]
If you're talking about the isolated storage files, delete the folders under `%AppData%\local\MarkdownEdit`

**Comment by RoyiAvital** [comment]
@mike-ward, I thought this is what we moved to the Local Folder of the application.
Could we have a version which also avoids that?

Thank You.

**Comment by mike-ward** [comment]
There are two folders (well three actually) folders in `%AppData%`, `local` and `roaming`. The settings you're concerned about are in `roaming` and those are the ones that have been moved when in portable mode.

Again, this is not a, "leave no trace" solution. A few settings like recent files and last window position will be written to the target system in `local`.

**Comment by RoyiAvital** [comment]
@mike-ward , If this is not much of an effort, could they all move into the local folder?

Moreover, see the issue I'm having with some of the settings.
From my previous post:

> P.S.
> It seems this version doesn't "Save" the GitHub MarkDown and Yes, I Donated! settings (I didn't change other settings and I did donate :smile:).
> Each time I open it, they go back to their default value.

**Comment by mike-ward** [comment]
Just tried it here and it works as advertised. (Ran if from a USB stick).

**Comment by RoyiAvital** [comment]
OK,
I ran it once form a folder on the Desktop.
Then it thought it was installed and didn't created local settings folder.

I moved it to a different drive.
It created that folder yet it won't save the states of those check box.

**Comment by shnbwmn** [comment]
@mikjsmith Just letting you know that I've created the [submission post](http://www.portablefreeware.com/forums/viewtopic.php?f=4&t=22927).

**Comment by RoyiAvital** [comment]
Can't wait to see official nee release of MarkDown Edit with Portable Version.

I still have the issues with the Donation Check Box.

Thank You.

**Comment by mike-ward** [comment]
Paypal: mike@wardfam.org :smile: 

Probably this weekend. Neither of my kids my US Nationals this year so I get free weekend.

**Comment by mike-ward** [comment]
@shnbwmn Thanks for doing this. Didn't know about wkhtmltopdf. Is this preferred converter?

**Comment by shnbwmn** [comment]
Not really, it's just a great tool (it's my go-to tool for converting web pages to properly-formatted PDFs). I mentioned it specifically on the post because the user needs to configure the path to its executable.

**Comment by RoyiAvital** [comment]
@mike-ward , I already donated when you implemented the Portable version.
But no matter what I do, it won't save the state of the Donation Check Box.

**Comment by mike-ward** [comment]
@RoyiAvital Open a new issue about this.

**Comment by RoyiAvital** [comment]
A Nice read about the subject:

https://www.quora.com/Is-it-better-to-run-portable-apps-software-instead-of-installing-the-full-version-on-the-computer
