### ISSUE TITLE
Pasting link sometimes doesn't convert it to MD link

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#107]
I like the feature of MDE where you just select text and press Ctrl+V to turn it into a Markdown link. However, this doesn't work for me in some cases:

![mde-paste-link](https://cloud.githubusercontent.com/assets/101152/12778126/5b6fb18e-ca61-11e5-9451-684955e15268.gif)

I was not able to track down when and why this happens, I will try to observe it to find out more about it.

**Comment by mike-ward** [comment]
Probably a bug in the pattern matching. Nice gif. Illustrates the problem clearly. :+1:

**Comment by mike-ward** [comment]
This occurs in HTML blocks which, is by design. In HTML blocks, Markdonw doesn't make sense.

**Comment by borekb** [comment]
It does also happen outside of HTML contexts. The simplest reproducable case is this:

```
<img src="" />

Link

Some other text
```

If you paste over the "Link" text (which is a new paragraph) it doesn't work.

Interesting is that if you remove the "Some other text" part, it starts working again. I don't get why it would do that but it might be some clue..

**Comment by mike-ward** [comment]
Looks like when it's also in proximity of an HTML block (within one line) it fails. Probably one of those famous off by one errors. I'll look into it further.
