### ISSUE TITLE
Inserting image link issues

### ISSUE THREAD

**Issue by cyotek** [mike-ward/Markdown-Edit#112]
Hello,

Couple of minor issues I noticed when dragging images from file explorer to MDE:

1. When inserting file paths, MDE chooses to insert absolute paths, even if the source image is located in the same folder as the MD document. Would be much more helpful if these were relative - I honestly can't think of a single reason why you would want a full path "hard coded" into a document
2. After choosing an option (well, I say option but I've only ever used **Insert Path**) the menu remains open. Again, I can't really see you choosing multiple options for the same file
3. It would be helpful if MDE was fully activated after dropping a file - for example try dropping an image file into a Word document. Word will insert the image and then fully bring itself to the foreground etc. I think this is more convenient. On the occasions where I'm dragging multiple items, I just tile windows side by side.
4. Speaking of multiple items, if you drag multiple image files in a single operation, MDE ignores all bar the first

5. Finally, a minor enhancement. I have no interest in Imgur, data URI's, or whatever the odd looking local file is. I create and process my images as separate entities and I want to link them in MD files, simple as. It would be nice if you could specify a default behaviour, so that when I drag and drop a file, a (relative ;)) link is created without any further interaction. I suppose if you wanted to be awesome, you could add an override key (File Explorer's right click drag is a good example) where the original menu would then be present for the one off scenarios you want to do something different.

(OK, so that's more than a couple - maybe I should have created separate issues, but don't want to spam. Also didn't think of testing the multiple file drag until I was halfway through writing the ticket)

**Comment by mike-ward** [comment]
This is awesome feedback. I'll address the issues individually a bit later but just wanted to acknowledge the thoughtful feedback.

**Comment by mike-ward** [comment]
1. Agree, paths should be document-relative.
2. The menu remaining is a bug. Not my intention.
3. Agree, app should fully activate
4. Didn't consider multi-file support. What if there are multiple file types?
5. Probably just add a settings option (file only)

**Comment by cyotek** [comment]
For 4, I did a test with non-image types and noted that MDE opened the file for editing, even if it couldn't possibly edit it (I tried dropping a text document followed by a shortcut). Maybe if a document is already open dropping any sort of file should just create a link (either image or just a standard link - you could either be lazy and have a predefined list of image extensions, or you could query HKEY_CLASSES_ROOT\.<Extension> and look the mime type or perceived type to decide what to do)

So, if it's a mix of content types (or more than one file in the drop) then I would link them all. If it's a single non-image file then that's a different story. Personally, I'd rather it linked - if I want to open a new document I am explicit in my intent, either by Control+O, or opening the file from explorer etc). But other users may like the open document on drag behaviour so maybe it's time for another hidden setting?

As for 5, that is fine with me.
