### ISSUE TITLE
Layout and scale problem on HighDPI displays

### ISSUE THREAD

**Issue by jry2** [mike-ward/Markdown-Edit#113]
Probably related to closed https://github.com/mike-ward/Markdown-Edit/issues/71

I can reproduce this problem on Windows 7 and Windows 10 with latest MDE 1.23 when I use 150% or 200% DPI for Windows desktop. MDE Preview window is up-scaled so right and bottom border (and some content) is clipped. Also content is blurry.

Problem is related to AirspaceDecorator and Microsoft.DwayneNeed.dll library.
Some details: 
https://microsoftdwayneneed.codeplex.com/workitem/10930
https://github.com/MahApps/MahApps.Metro/issues/488

I did some quick&dirty hacks and removing `<interop:AirspaceDecorator x:Name="PreviewAirspaceDecorator"...> and </interop:AirspaceDecorator>` from Preview.xaml and commenting out `PreviewAirspaceDecorator.Visibility = state == 1 ? Visibility.Collapsed : Visibility.Visible;` in `UpdateEditorPreviewVisibility()` works for me.

I also compiled fixed fork of AirspaceDecorator from https://github.com/barbeque/DwayneNeed mentioned at http://nondisplayable.ca/2015/05/29/mahapps-metro-gotchas.html and it works for me too, without any changes to MDE source code (just replace these two DLLs with fixed version). I used only patches from RedirectedHwndHost.cs and RedirectedWindow.cs files, all other source files were from https://microsoftdwayneneed.codeplex.com/SourceControl/latest

Please see attached screenshots. Note: these two controls above WebControl and margins around are there just for my tests.

I hope it will help to solve this issue. MDE looks great btw!

![test](https://cloud.githubusercontent.com/assets/10026109/13030634/e2531152-d2b1-11e5-97e3-6971e44c7205.png)
![problem](https://cloud.githubusercontent.com/assets/10026109/13030635/ec59c506-d2b1-11e5-95fd-3cf9b965273d.png)
![fix](https://cloud.githubusercontent.com/assets/10026109/13030638/f1b14d1c-d2b1-11e5-971b-410a696ebe68.png)

**Comment by mike-ward** [comment]
Nice work! Really appreciate your efforts. I will happily add the new DLL's to the distribution.

**Comment by sualeh** [comment]
Finally! Thank you!
