### ISSUE TITLE
Broken Editor and Preview scroll synchronization

### ISSUE THREAD

**Issue by jry2** [mike-ward/Markdown-Edit#114]
To reproduce this problem just start MDE, press F1 and scroll to line 6:
![sync](https://cloud.githubusercontent.com/assets/10026109/13032348/4b857c9a-d2ef-11e5-8c65-cb38ad75ff27.png)

Preview will scroll beyond Keyboard Shortcuts block so it is not possible to edit it while viewing on Preview.

Just idea: would it be possible to implement linear approximation of anchors and scroll offset in Editor and Preview?

**Comment by mike-ward** [comment]
Linear scrolling is what MDE use to do. It doesn't work for a whole host of reasons. It does work on (very) short documents with no images.

MDE injects anchors into the HTML and then scrolls to the nearest anchor. Anchors are calculated using an Abstract Syntax Tree that is generated when the preview is built. The AST only knows about block elements (not entirely true but for this conversation it suffices). Block level elements include paragraphs, headers, HTML blocks, etc.

What you're seeing here is a large HTML block. The reason for the large HTML block is to get a fixed layout in the preview. This is a weakness of both MDE and the Markdown syntax. A table might be a better approach but the Commonmark variant of Markdown does not support tables at this time.

If there's a line by line scroll sync that works with Markdown, I've yet to see it.

It might be possible to use a hybrid approach where it uses a block anchor plus linear offset but even that will break down in larger blocks.

I"m open to suggestions on how to enhance this.

**Comment by jry2** [comment]
Thank you for the thorough explanation. I thought about it today and hybrid approach seems to be better solution compared to current state. It could kick in when previous anchor is above Editor view and next anchor is below the (Editor) view so it would not affect current behavior. It could use linear function you had in old MDE versions, but in this case it would be bound to mentioned anchors, not to whole document. What do you think?

**Comment by mike-ward** [comment]
That's pretty much what I was suggesting. Anchor plus offset.
