### ISSUE TITLE
Broken link in README.md 

### ISSUE THREAD

**Issue by jry2** [mike-ward/Markdown-Edit#116]
Display Equation Markup - http://markdownedit.com/markdown-edit-math-equations/

**Comment by cben** [comment]
404 again, without the / too.
I suppose the source is https://github.com/mike-ward/Markdown-Edit/blob/gh-pages/_posts/2015-11-30-markdown-edit-math-equations.md
ah, found: http://markdownedit.com/2015/11/30/markdown-edit-math-equations.html

While here, I also wanted to ask about `\\(...\\)` syntax.
- That post recommends `\\(` and says `$` needs special configuration.  BTW, did it mean double or single backslash?
- http://markdownedit.com/assets/js/mathjax-scripts.js IIUC sets up rendering of single backslash `\(` (that's what `'\\('` stands for in JS) as well as `$`.
- When running pandoc you only enable `tex_math_dollars` extension.  Should probably add [`tex_math_single_backslash`](http://pandoc.org/MANUAL.html#extension-tex_math_single_backslash) (or double) if you want that to work.
- Wait, does `\\(` work by pandoc translating it to single `\(` then MathJax running?
  If so, that is vulnerable to what looks like "markdown" getting formatted inside formulas, eg. `\\({a}_{2i} + {a}_{2i+1}\\)` turns into `<p>\({a}<em>{2i} + {a}</em>{2i+1}\)</p>`, or worse cross-formula `\\(a*b\\) + \\(c*d\\)`.  It's much better to let Pandoc parser be aware of the math.
