### ISSUE TITLE
Occasional crashes on MDE exist

### ISSUE THREAD

**Issue by jry2** [mike-ward/Markdown-Edit#118]
I'm unable to reproduce this problem each time I exit MDE but I saw it multiple times, just when I press Alt+F4 and choose No for Save confirmation. Windows 7 x64, MDE builded from latest source code. Do you have any idea what the problem could be? I'm not 100% sure but I think I saw crash on exit in version 1.23 installed with official installer.

Exception:
> An exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in WindowsBase.dll but was not handled in user code
> Additional information: A task was canceled.
> If there is a handler for this exception, the program may be safely continued.

Callstack:
> mde.exe!MarkdownEdit.Controls.Editor..ctor.AnonymousMethod__23_2(string s) Line 65	C#
> mde.exe!MarkdownEdit.Models.Utility.Debounce.AnonymousMethod__1(System.Threading.Tasks.Task task) Line 44	C#

Line:
`_executeAutoSaveLater = Utility.Debounce<string>(s => Dispatcher.Invoke(ExecuteAutoSave), 4000);`

![crash](https://cloud.githubusercontent.com/assets/10026109/13035960/6f682998-d35b-11e5-8be1-1b550d0ec303.png)

**Comment by mike-ward** [comment]
So is this a crash or just an unhandled exception in the debugger?

**Comment by jry2** [comment]
I'm not 100% sure and I'm not able to reproduce it now. I will keep an eye on it next time.
