### ISSUE TITLE
Suggestion: Imgur integration

### ISSUE THREAD

**Issue by philoushka** [mike-ward/Markdown-Edit#12]
I often have a screenshot ready to place in my markdown document.

Currently the workflow is:

* save an image to disk on my machine
* upload to Imgur myself in the browser
* copy paste that img url into the markdown document

Would you consider creating a feature whereby the user could:

* Ctrl-V to paste an image on the clipboard or:
  * trigger a file dialog box
  * pick an image
* MDE uploads that file to Imgur
* MDE creates an `![](http://my.new.imgur.url)` in the document

**Comment by mike-ward** [comment]
The image integration in MDE is pretty weak at the moment. I have a different workflow using GitHub Pages so something more generic is preferred. What that "more generic" thing is I'm not sure.

Some thoughts to kick off brainstorming.

- Picking an image from the file dialog box is limiting. Currenty, if you drag and drop an image to MDE it will insert the file name. Extending this to trigger an upload/dowork option might work

- The upload/dowork option might be as simple as having a power shell script with a fixed name that executes whatever actions are are required. User supplies powershell script. We can keep a list of useful example scripts on the web.

Haven't thought more about it beyond this. Suggestions welcomed.

**Comment by philoushka** [comment]
I'd be happy to see a combo of all the above, especially the PowerShell
script idea. That keeps it open to the user's image repository of choice.
I'd be happy to write/contribute the Imgur upload script and others.

I like MDE's aesthetic of:

- keyboard shortcuts
- minimal dialog boxes
- user-supplied scripts

As a user, I'd be happy if that upload script could be triggered on events
like:

- mouse drag and drop an image onto the document
- user pastes (Ctrl-V) an image on clipboard (not a path, but an img)
- a file chooser dialog if you choose

As you say, provide popular/common scripts in a dir on GitHub, etc.

**Comment by mike-ward** [comment]
I looked at the Imgur API. It requires OAuth and several handshakes. Nothing awful but probably outside the purview of a PowerShell script. Why don't we start with Imgur as you suggest. I'll create a branch and register the app with Imgur so we can get an API key.

I recommend implementing an `IAddImage` interface (or other descriptive name) so we can add additional implementations.

For a keyboard shortcut, let's try `Ctrl+Shift+V`. That makes it an explicit, opt-in, action and keeps the `Ctrl+V` logic closer to what is normally expected.

There's a recent NuGet package for Imgur that might be useful.

**Comment by mike-ward** [comment]
OK, here's the Imgur client ID for Markdown Edit:

client_id: 68a0074c7783fd4

Create a branch and have at it. Thanks!

**Comment by mike-ward** [comment]
I've implemented this feature via drag'n'drop. Drag an image onto the editor and it offers to paste the path or upload to imgur. Email me for a download address. I would like to get some feeback on this before releasing it.

**Comment by mike-ward** [comment]
Implemented in 1.4
