### ISSUE TITLE
MDE install path

### ISSUE THREAD

**Issue by jry2** [mike-ward/Markdown-Edit#121]
MDE is intstalled (on Windows 7) to C:\Users\user_name\AppData\Local\MarkdownEdit\bin\mde.exe. It would be nice to have option to install it to standard Program Files (x86) path where it is protected by UAC.

**Comment by mike-ward** [comment]
I see no advantage to doing this. It complicates the install experience by requiring privilege elevation, excludes users who don't have admin privilege (corporate systems) and offers little additional security.
