### ISSUE TITLE
Unintended Preview window closing

### ISSUE THREAD

**Issue by jry2** [mike-ward/Markdown-Edit#122]
Open MDE, left-click the Preview pane, press Alt+F4. Preview pane will be closed instead of MDE.
I assume this is a bug rather than intended behavior?

**Comment by mike-ward** [comment]
Yep, its a bug. Thanks for reporting it.

**Comment by mike-ward** [comment]
Close as I can get is to shut down the app (which is what `Alt+F4` does). However, if there are unsaved changes, it will prompt and if you cancel, the preview window closes. Tried to intercept the `Alt+F4` but the browser control snatches it first. Even tried COM sinks (talk about your old school).
