### ISSUE TITLE
Live preview on 3840x2160 v. small

### ISSUE THREAD

**Issue by HamptonNorth** [mike-ward/Markdown-Edit#124]
Great product. Was using on Win 10 laptop with 1920x1080 screen and all fine.

Moved to Win 10 3840x2160 screen (Dell XPS 15) - editor sizing fine but live preview panel too small.

![2016-02-26_12-05-36](https://cloud.githubusercontent.com/assets/1650551/13351842/71c8786c-dc81-11e5-836c-ab01614c9064.png)

Went back to original and updated to ensure both 1.24

Any suggestions?

**Comment by mike-ward** [comment]
You can zoom the preview view using CTRL+MouseWheel. (Same as most browsers).

**Comment by HamptonNorth** [comment]
Thanks for timely reply - I should have been more specific - When I *saveAs* a
*.pdf the output is not scaled correctly. I've tested saving as .html and
as .docx and they are both perfect.

I have attached screen shot:

1 - shows preview panel zoomed to comfortable size as per your response
2 - Correctly scaled *.pdf from 1920x1080 screen laptop
3 - Incorrectly scaled *.pdf from 3840x2160 screen laptop

I reported the issue initially as I had assumed the livePreview panel
sizing was linked to the *.pdf scaling - it is not

Thanks again for great product

Rob

(H) 0151 651 0215
(M) 07713 625009

**Comment by mike-ward** [comment]
I'm a bit surprised that resolution would effect PDF output. Thanks for reporting this.

**Comment by HamptonNorth** [comment]
![2016-02-26_14-12-53](https://cloud.githubusercontent.com/assets/1650551/13378964/f8b09f0a-de0f-11e5-800b-04aaae19cf11.png)
