### ISSUE TITLE
table text overlapped when splitting over pages

### ISSUE THREAD

**Issue by jonathanb123** [mike-ward/Markdown-Edit#126]
see wkhtmltopdf issue https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1524

Suggested fix add `page-break-inside: avoid;` to `tr{}` in user_template.html

    #content table tr {
      background-color: #fff;
      border-top: 1px solid #ccc;
      page-break-inside: avoid;
    }

**Comment by Yaroslav-F** [comment]
This fix seems to work for me. +1

**Comment by mike-ward** [comment]
Thanks for hunting this one down guys.
