### ISSUE TITLE
GitHub-like Emoji rendering

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#128]
I cannot believe that I'm filing this but I so got used to Emoji on GitHub now that I'd like to see them rendered the same in MDE preview.

If I'm not mistaken, Pandoc and their `:emoji:` to unicode character conversion is currently being used (https://github.com/mike-ward/Markdown-Edit/issues/66). Maybe there could be an option (config file is enough, no need for UI) to instead use GitHub CDN and an image. For instance, the :tada: emoji is rendered like this:

```
<img class="emoji" title=":tada:" alt=":tada:"
src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f389.png"
align="absmiddle" height="20" width="20">
```

**Comment by mike-ward** [comment]
Clearly you've gone off the rails on this one :smile: 

I would need a map to of text to emoji id. Is there one available?

**Comment by mike-ward** [comment]
I found this. http://hassankhan.me/emojify.js/

This looks promising. Exporting to HTML would present some problems since the assets are local.

**Comment by borekb** [comment]
Could you just take the Unicode char's code and put it to that assets-cdn.github.com URL? Seems to me that the image name is `<character code>.png`.

**Comment by mike-ward** [comment]
That's why I was asking about a map. That's a tedious job I'm not interested in. Now if someone handed me a map of unicode characters to URLs... :smiling_imp:

**Comment by borekb** [comment]
This is the map (pseudocode):

```
function getHtmlFragment(emoji: UnicodeChar): string {
    var charCode = emoji.getCharacterCode();
    return '<img ... src="https://assets-cdn.github.com/images/icons/emoji/unicode/' + charCode + '.png" />';
}
```

**Comment by mike-ward** [comment]
The mapping function isn't the issue. The question is, which Unicode characters are eligible for translation? Can't just translate any Unicode char.

I need a **list** of Unicode characters that represent emojis.

Also, I would opt for doing this before rendering. Doing it in JavaScript means having to add a listener to the `previewUpdated` event. I had to add this event to use MathJax. It's not an ideal solution since it introduces a "jump" when the view updates. Unfortunately, the way MathJax loads scripts requires browser-side rendering. I would like to avoid this with the emojis.

Also, to make this feature useful, some kind of autocompletion functionality in the editor should be added.

**Comment by mike-ward** [comment]
Found it: https://developer.github.com/v3/emojis/

**Comment by mike-ward** [comment]
So my thinking is I'll remove the Pandoc emojis and add these in instead. It does mean you have to be online to see the emojis. Is that OK?

**Comment by borekb** [comment]
What would I see when offline? (I am offline quite frequently.)

**Comment by mike-ward** [comment]
A broken image

**Comment by borekb** [comment]
Two solutions come to mind:

1. Detect online / offline and use GitHub images or Pandoc as appropriate.
2. Cache the images locally, either on-demand or I wouldn't even mind a one-time "download all images" command that would loop over the GitHub emoji list and fetch all the images for local use.

I understand though that you probably don't want to spend too much time on this :) So in the worst case, I can live with broken images preview, or even no previews at all when offline (it would probably be better to see `:tada:` in the preview than a broken image indicator).

**Comment by mike-ward** [comment]
Time is not the issue. Most of this stuff doesn't take much time to code. Most of my time is spent trying to figure out the right thing to do.

As to caching images, there are other possibilities. 

- A sprite would be the most efficient way to handle local resources (generating one might be hard however).
- Local browser caching is another possibility.
- Injecting Data URI's.

And as I eluded to earlier, autocompletion (like what GitHub does) would make the feature more useful.

**Comment by borekb** [comment]
Found a couple of interesting projects like https://github.com/Ranks/emojione. Not sure if directly useful but might be another option.

**Comment by borekb** [comment]
> And as I eluded to earlier, autocompletion (like what GitHub does) would make the feature more useful.

Agreed. Do you want to track it here or should I create a new issue for that? (Autocomplete functionality can be built and tracked separately.)

**Comment by mike-ward** [comment]
This issue is fine for now. Thanks.

**Comment by mike-ward** [comment]
OK, I have an initial implementation of emotions at:

http://www.expirebox.com/download/9389c773444c28b6762965be85e6230a.html

To use it:

- install
- Delete the `user_template.html` in your `App_Data` roaming folder
- This works offline (uses a sprites file)
- Send feedback

There's no autocompletion in the editor.

**Comment by borekb** [comment]
Works very nice! There are just small rendering artifacts, possibly due to the sprites file method (not sure):

![image](https://cloud.githubusercontent.com/assets/101152/13907389/49d00950-eeed-11e5-9e74-f130aa68aa66.png)

But it's _much_ nicer than Unicode chars. :+1:

**Comment by mike-ward** [comment]
The bitmaps are 64 px. I suspect it's an artifact from resizing.

**Comment by borekb** [comment]
Are there major advantages to having one large PNG vs. hundreds of small ones? I guess that would get rid of these rendering artifacts.

**Comment by mike-ward** [comment]
What makes you think the sprite is the source of the rendering artifact?

**Comment by borekb** [comment]
The fact that I've never seen those artifacts e.g. on GitHub where the images are separate PNGs. But I could very well be wrong.

**Comment by mike-ward** [comment]
It appears to be a scaling artifact. Try scaling the image using your mouse wheel in the preview. You'll see the artifact change size and sometimes disappear depending on zoom level. That being said, it's likely that rendering the image as a background element (the sprite technique) is partly to blame.

To answer your question of why a sprite, it's simply a deployment logistic. The resources for MDE are stored in the program itself. That way if the user messes up their stuff, it can simply be deleted and MDE restores it. To apply the same technique to 900 images would not scale. it would require a file watcher for each item. The system would crawl.

Now I know you're thinking that I shouldn't have to do it, but that's how it works with templates, snippets, etc. Not doing it for the images would be weird. Plus the images would have to be installed somehow. Likely the installer. So the burden of getting them on disk and maintaining them remains. The sprite reduces that headache to one file.

The other way to store the images is as Data URI's. That has a some advantages in that the exported document would be standalone. It also means I can treat the emoticons and simple images. I'll explore this option next.

**Comment by mike-ward** [comment]
Found a simpler fix. Just changed the zoom level in the template from 0.4 to 0.39.
