### ISSUE TITLE
Touchpad scrolling is way too fast

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#129]
On my laptop with ["precision touchpad"](http://windows.microsoft.com/en-us/windows-8/touchpad) most apps scroll beautifully but MDE is very, very rapid - I barely touch it and it scrolls two pages (exagerating a bit but you get the point). The scrolling is almost unusable in MDE. Is there a quick fix for this in the technology MDE uses?

**Comment by mike-ward** [comment]
I'm assuming you're talking about the editor and not the preview.

Can't think of a reason why this should happen. Editor scrolling is mostly an Avalon Edit thing. I don't use the scroll pad on my laptop so I'll have to check it out tonight when I get home.

**Comment by mike-ward** [comment]
Yeah, it's pretty fast on my setup as well. Wonder if it's a WPF thing? Not finding anything on the Web about it.

**Comment by borekb** [comment]
I'm sorry I can't help here as I don't know WPF much. Perhaps it's something that AvalonEdit guys could help with? Maybe it's an issue in that component in the first place?

**Comment by mike-ward** [comment]
I found something that might help. Here's a link to a quick build.

http://www.expirebox.com/download/fb98ee681680725937e14f955391fe28.html

Let me know if it helps.

**Comment by borekb** [comment]
Yes that's a huge improvement. Nice!

**Comment by mike-ward** [comment]
Turns out WPF is scrolling is a hot mess. There's a library I found on the Code Project that addresses issues like this. It also makes the scrolling a bit smoother overall. So I'm a genius (at searching the Internet).
