### ISSUE TITLE
Images don't render

### ISSUE THREAD

**Issue by generateui** [mike-ward/Markdown-Edit#13]
1. save file to location x
2. ensure in same directory image exists e.g. `cat.png`
3. add image syntax e.g. `![cat](cat.png)`

Note that the image is not rendered in the preview, only a placeholder.

Windows 8
Markdown-Edit 1.3.5

**Comment by mike-ward** [comment]
Umm... Just tried as you described and it works. Is the image valid?

**Comment by generateui** [comment]
No. Funny: a random image plucked from the web turned out to not render for some reason. Tried many other random images without fail. Glitch in the matrix?
