### ISSUE TITLE
IgnoreYaml doesn't work

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#131]
My user_settings.json contains `"IgnoreYaml": true`, however, I still see the front matter being rendered:

![2016-03-23 10_35_11-clipboard](https://cloud.githubusercontent.com/assets/101152/13981215/f3c4a92e-f0e2-11e5-92a1-cf9d896e750e.png)

**Comment by mike-ward** [comment]
Oops, forgot to remove that option. I removed it when I went to a a new scroll algorithm.

**Comment by borekb** [comment]
Would it be technically possible to add this feature back, in a way that works with the new scrolling algorithm? Would be very useful when authoring documents for Jekyll etc.

**Comment by mike-ward** [comment]
Useful how?

**Comment by borekb** [comment]
The front-matter is currently rendered as if it was a heading, see the screenshot above, which is kind of ugly. No big deal but the `IgnoreYaml` option was an elegant way to get rid of it.

**Comment by mike-ward** [comment]
Does adding a blank line after layout work? It won't be a header then.

**Comment by borekb** [comment]
It would help the rendering but no one writes front-matter like that. I quite like how GitHub renders it ([example](https://github.com/wp-cli/wp-cli.github.com/blob/master/docs/commands-cookbook/index.md)), but just hiding it altogether as MDE used to would be best and sounds like a simple thing to do. But maybe there are technical issues with that related to scrolling as you mentioned, I don't know.

**Comment by mike-ward** [comment]
It's possible but harder than it sounds. One has to calculate the height of the front matter in preview to subtract it (or is it add?) from the scroll offset. Calculating this generally requires rendering it.

**Comment by borekb** [comment]
Could it be just removed from Markdown using a regex and then rendered?

**Comment by mike-ward** [comment]
That's how it worked before. Still have to figure out how to vertically align the views. It's not a simple offset or percentage of scroll height type calculation (the original algorithm).

**Comment by borekb** [comment]
I see. It's no big deal if it's too hard to implement properly.
