### ISSUE TITLE
Curly quotes

### ISSUE THREAD

**Issue by BarneyFifeFan** [mike-ward/Markdown-Edit#134]
According to [Practical Typography](http://practicaltypography.com/straight-and-curly-quotes.html), among others, curly quotes are considered to be best practice for writing documents. Unfortunately, users of ME are currently stuck with using Alt key combinations to insert curly quotes. Could automatic curly quote insertion (i.e. "smart quotes") be added as a feature to ME--perhaps with a settings toggle to be turned on and off per user preference?

**Comment by mike-ward** [comment]
Snippets to the rescue!

Add `"         “$END$”`

to your keyboard snippet file.

Type `"+TAB`

**Comment by BarneyFifeFan** [comment]
Maybe I'm doing it wrong, but this fix produces unknown characters in ME when I tried it (as in ��).

**Comment by mike-ward** [comment]
You need an editor that encodes in utf8. Notepad uses windows 1252. I like notepad2 for this reason.

**Comment by BarneyFifeFan** [comment]
Works great for quotes. However, single quotes (particularly when used as apostrophes) still need to be addressed.  I would apply this to them by modding, but the apostrophe wouldn't work.

**Comment by mike-ward** [comment]
This works for me:

'         ‘$END$’
