### ISSUE TITLE
New version incorrectly suggested

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#136]
I just received a new version notification even though there's nothing newer than 1.25.1 and I'm on that version:

![image](https://cloud.githubusercontent.com/assets/101152/14171998/3e20af28-f736-11e5-9fbc-3db2e56b4037.png)

**Comment by mike-ward** [comment]
Not seeing it here.

It gets the version number from: http://markdownedit.com/version.txt

**Comment by borekb** [comment]
Not seeing it now either. I remember there were network problems at that time so maybe the request returned something like `500 ...` and it translated to version number 500 and prompted for update, or something like that.

**Comment by mike-ward** [comment]
It should just ignore a bad network connection or 500 response.

https://github.com/mike-ward/Markdown-Edit/blob/master/src/MarkdownEdit/Models/Version.cs

**Comment by borekb** [comment]
Ah so maybe if the shopping mall WiFi returned a login HTML instead of `1.25.1` (as those public WiFi's commonly do), that method returned `false` and I was prompted for update.

**Comment by mike-ward** [comment]
That's a possibility. Guess I'll have to add some sanity checks check the response (numbers and periods only for instance).
