### ISSUE TITLE
Re-number list when an item is deleted

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#138]
When I have a list like:

```
1. First item
2. Second item
```

and press Enter at the end of the first line, this is the result:

```
1. First item
2. |
3. Second item
```

Which is good – 2 was automatically changed to 3.

It would be good if the same worked the other way around, i.e., if I now delete the line starting with `2.`, it would change `3.` back to `2.`. I can imagine that the implementation would be a bit tricky (it harder to detect "line was deleted" compared to "line was added") but it would be useful.

**Comment by borekb** [comment]
BTW, the "format" command (`Alt+F`) re-numbers the list but I usually don't want to full formatting, just to fix the numbers of the ordered list.

**Comment by mike-ward** [comment]
Took a while to get to this one. Surprising challenging problem getting this to work. Look for it in the next version.
