### ISSUE TITLE
Fonts with ligatures render in HTML, but not preview or PDF

### ISSUE THREAD

**Issue by elizhenning** [mike-ward/Markdown-Edit#139]
I've loaded the Google webfont Radley on the HTML template, and it looks very nice in preview, PDF, and HTML. However, the HTML version in the browser has ligatures--Radley in particular has a decorative "ck" ligature in addition to the standard ligatures--but neither the preview nor the exported PDF do. This isn't really bothering me, but it does suggest something about how fonts are being handled that might be important.

**Comment by mike-ward** [comment]
I'm using a third-party converter. Likely that's the issue. In the meantime, Can you use one of the free PDF converters that installs as a printer? Then right click on preview and print.

**Comment by elizhenning** [comment]
Sure, I should have said that. This issue isn't an actual problem, I just thought it was weird and wanted to point it out.

**Comment by mike-ward** [comment]
Just looking for a workaround until I can determine the problem.

**Comment by mike-ward** [comment]
This appears to be an Internet Explorer issue. If I view the Google Font Page (https://www.google.com/fonts/specimen/Radley) in IE I don't see the ligature. It does appear in Chrome.

See https://stackoverflow.com/questions/14145121/ligatures-in-internet-explorer

**Comment by elizhenning** [comment]
I don't use IE. The issue isn't the HTML file, it was the live preview and built-in PDF export for Markdown Edit.

**Comment by mike-ward** [comment]
The live preview uses IE :smile:
