### ISSUE TITLE
Toolbar: Some icons not shown

### ISSUE THREAD

**Issue by matidio** [mike-ward/Markdown-Edit#14]
I have some problem with the visualization of the toolbar icons. Some of them are shown only as file icon (see attached screenshot). Installation was ok, no issues. I have no idea where to look to resolve this. The problem exists since v1.3.5.

Windows 7 x64
![markdown edit - no icons](https://cloud.githubusercontent.com/assets/7942410/6938761/35fe99ee-d866-11e4-82c6-5b9d64a5f4fe.jpg)

**Comment by mike-ward** [comment]
Some of the icons in the Segoe Symbol font are only available in Windows 8.

**Comment by mike-ward** [comment]
This link has newer fonts. Use the Windows 8.1 font.

http://media.askvg.com/downloads/2013/01/Install-Segoe-UI-Symbol-Font-in-Windows-8.zip

**Comment by tiesont** [comment]
I guess I don't really get why this is "won't fix" - the requirements listed on the home project page says "Windows 7+". If the UI requires Windows 8 fonts to display the menu glyphs, it makes the app a little less "user-friendly" to have to hover and wait for the tooltip text.

Have you considered possibly embedding something like Font Awesome? It's [license](http://fortawesome.github.io/Font-Awesome/license/) allows use in "desktop" apps. If you're willing to re-open this issue, I'd be willing to take a stab at switching the glyphs.

**Comment by mike-ward** [comment]
I appreciate the offer. I've used the font awesome fonts in other desktop apps and they look "odd" when compared to the system icons. It's just not something I'm interested investing energy in.

**Comment by jnm2** [comment]
If the font isn't installed with the software, it's a bug. I'm sorry you don't think it's worth spending time fixing, but next time I want to install this it's not gonna be worth my time forgetting this and digging up this link and manually installing a font every time.

**Comment by mike-ward** [comment]
Microsoft's licensing does not allow me to distribute the font. Distributing the any font would require elevating the installer privilege to admin which I'm not willing to do. It's not a bug, it's a choice.

**Comment by jnm2** [comment]
I have five machines and do clean installs every now and then. So I'm an extreme case, but choosing to take a dependency you can't distribute and not even providing a link to instructions on startup when the dependency is missing doesn't impress like it could.

**Comment by mike-ward** [comment]
Point taken. I will add a link to this issue on the MDE home page and make it abundently clear that Windows 7 is not supported (for any issue).
