### ISSUE TITLE
MathJax doesn't render left subscripts (conflict w Markdown)

### ISSUE THREAD

**Issue by elizhenning** [mike-ward/Markdown-Edit#140]
An expression like ` _{B} A_{C} ` should render as the letter A with a left subscript B and a right subscript C, but it doesn't.

**Comment by mike-ward** [comment]
If MathJax conflicts with CommonMark. who should win?

**Comment by elizhenning** [comment]
I've tried this with a few other Markdown + MathJax applications that also recognize underscore as italic (which I dislike anyway--I use asterisks) and it renders correctly. No idea what's going on under the hood. Maybe an option to choose delimiters?

**Comment by mike-ward** [comment]
Still doesn't answer the question.

I'm going to call this and say that Markdown comes first, then other markup dialects. That may be in contrast to other apps but I don't see how putting other dialects before Markdown can cause anything but confusion.

There's an option to choose delimiters in MathJax but it does require editing the template.
