### ISSUE TITLE
Auto save

### ISSUE THREAD

**Issue by UweKeim** [mike-ward/Markdown-Edit#143]
No matter in which position I do put the "Auto save" icon (I cannot find out what color means "on" and which means "off") — when having a document wich modifications and closing Markdown Edit, I got prompted whether to store my changes.

I would have expected that at least one of the two colors of the "Auto save" icon would actually do an auto-save?!?

**Comment by mike-ward** [comment]
Just tried it here and it appears to be working fine. Keep in mind the document must be saved at least once. Otherwise, the program does not know where to save it to.

The on color for autosave is the same on color as the other icons.

**Comment by UweKeim** [comment]
The file _was_ saved before.

**Comment by mike-ward** [comment]
And if autosave was really broken you don't think I would have heard about it before now?

Seriously, if you want help, I need specifics. Maybe your system has a unique configuration I've not considered in my design. Maybe you're doing it wrong. I don't know. At least walk me through what you're doing and why you think it's not working. A video screen capture demonstrating the issue would help.

**Comment by mike-ward** [comment]
You can also turn autosave on/off in settings dialog (`Ctrl+,`)

![image](https://cloud.githubusercontent.com/assets/567927/14641331/b90b4ed2-0613-11e6-92ec-1925a65c9ff3.png)

**Comment by UweKeim** [comment]
Thanks, Mike. No offense intended by me.

The behavior was on my old Windows 10 and also on my new Windows 10. I've accepted the behavior long time ago, so no need to change anything. :+1:

**Comment by UweKeim** [comment]
I finally did a repro:

[![IMAGE ALT TEXT](http://img.youtube.com/vi/K_FLrNzWDA0/0.jpg)](https://youtu.be/K_FLrNzWDA0 "Markdown Edit and the Auto-save function").

So basically it seems to work, but it fails when closing the document too quickly.

Probably the timer should be made to poll quicker and also if user is explicitely closing and auto-save is activated, it should store immediately.

**Comment by UweKeim** [comment]
Did my above comment from 13 May ever get noticed by the author?

**Comment by mike-ward** [comment]
Oops, missed it for some reason.

Buttons: It's a matter of opinion I suppose. The `on` position is much lighter than the darker `off` position. The hover color is an important queue that the item can be clicked.

I'll see if I can make this quick save bug happen. Tried before but was unsuccessful.
