### ISSUE TITLE
Please provide a less distracting syntax coloring scheme

### ISSUE THREAD

**Issue by UweKeim** [mike-ward/Markdown-Edit#147]
I suggested Markdon Edit to my co-worker, recently switched from Mac to Windows.

On Mac he _loved_ [iA writer](https://ia.net/writer/ios/).

He choose not to use it primarily because of the "awful" colors in the left editor area. (E.g. he strongly dislikes the purple for the headlines.

I know that he could change the HTML color codes, but this is against the idea of "[the power of defaults](https://www.nngroup.com/articles/the-power-of-defaults/)".

**My suggestion:**

- Please provide a more readable/elegant default color scheme, -or-
- Provide multiple color schemes and the ability to simple choose one of them via the GUI.

**Comment by mike-ward** [comment]
Try ctrl+T :)

**Comment by UweKeim** [comment]
Wow, awesome. Thanks a lot!

**Comment by UweKeim** [comment]
Would be awesome to provide a button in the settings dialog to show the <kbd>Ctrl</kbd>+<kbd>T</kbd> dialog.

Searched for 10 minutes through the options today, then gave up, searched this issue here and finally used the shortcut.

**Comment by mike-ward** [comment]
What do others think about this? Settings? Titlebar button? Somewhere else, Don't change?
