### ISSUE TITLE
Some problem in windows 7 about  edit verson 1.4  

### ISSUE THREAD

**Issue by waylau** [mike-ward/Markdown-Edit#15]
1.windows 下测试了 Markdown Edit，发现右上角的按钮图标显示不正常，都是方块，

2.对于 `##` 这样的标题， 预览也没有显示正常 ，

3.拖图进 Markdown Edit 提示上传了，但是一直看不到图。且无提示说要绑定 imgur 账号
对于表格，也看不到预览、

OK ，here is English 

1.When I tested in win7 about Edit 1.4 ，buttons on the top of bars display is not normal.

2.Like `##` title is not preview normal on the left

3.Drap image to  Markdown Edit ,see it uploaded ,but I can;t see image url in my edit , and I have not idea it is uploaded success or failed

**Comment by TongG** [comment]
你说的 “且无提示要绑定 Imgur 账号” 是什么意思？（Imgur 不需要注册和登录就可以使用）

**Comment by waylau** [comment]
@TongG   就是说，之前我怀疑是不是因为 没有账号 才上传失败了。如果不需要账号的话，他也是失败的，我托一个图进编辑器，他显示了上传进度条。接着 上传进度条消失了，按理是成功了。但是没有看到 生产 的image  url ，那就是失败了。



另外github 上图也失败了 老是提示“Something went really wrong, and we can't process that image.  Try again.”

**Comment by TongG** [comment]
应该是网络原因。Imgur 和 GiHub 最近在国内的网络状况都不怎么好。

**Comment by TongG** [comment]
需要你为第一条和第二条加上截图。

**Comment by waylau** [comment]
![001](https://cloud.githubusercontent.com/assets/3233966/6959815/3af868b4-d94f-11e4-854f-2383c97b1425.jpg)

**Comment by waylau** [comment]
哇嚓～，终于上图了~  @TongG

**Comment by TongG** [comment]
Translation (Chinese ⟹ English):

0. I run Markdown Edit 1.4 on Windows 7, it's very cool. However, the buttons lying in the top right corner of the title bar cannot be displayed correctly. 

1. Some Markdown elements (e.g. `##` label) cannot be rendered properly in the preview view on the right)

2. When I drag and drop the image onto Markdown Edit, it tells me that the image was uploaded, but I can't see the URL of image that just been uploaded in the edit field. I have no idea whether the image I selected was indeed uploaded successfully.

Just for clarifying my description, please see the following screenshot:

![3af868b4-d94f-11e4-854f-2383c97b1425](https://cloud.githubusercontent.com/assets/4256649/6959880/e9a8c304-d94f-11e4-894d-4f460f738953.jpg)

BTW: Thank you for this awesome program!

**Comment by mike-ward** [comment]
Known issue on windows 7 icons See issue #14 

You need a space between the `###` and text. See the Commonmark spec (http://spec.commonmark.org/0.18/#atx-headers)

Not see the image link inserted is a real bug. It may have something to do with localization. I don't know. Please log it as a separate issue.

**Comment by TongG** [comment]
Fine, thank you.
