### ISSUE TITLE
Code block looking bad while saving as PDF

### ISSUE THREAD

**Issue by rgarrigue** [mike-ward/Markdown-Edit#151]
Hi again

I got an issue with code block whenever I'm saving my document as PDF. They're quite wide and the output is cropped on the right side, with an horizontal scrollbar. How should I customise the template to get it to wrap, and if possible without scrollbar and a light grey background ? 

Best regards,

**Comment by mike-ward** [comment]
Do you have an example document?

**Comment by rgarrigue** [comment]
Here is a ![snap](https://cloud.githubusercontent.com/assets/1872031/15666122/439b337a-270f-11e6-8a2b-5d8f9d8fbaa4.png),

And the related piece of markdown

	Configuration

		cp /opt/wildfly/wildfly/standalone/configuration/config.properties /opt/wildfly/wildfly_9.x/standalone/configuration/
		sed -i -e 's/:8080/:18080/g' /opt/wildfly/wildfly_9.x/standalone/configuration/config.properties
		sed -i -e 's;https://portail-bgo.equade.fr$;https://portail-bgo.equade.fr:18843' /opt/wildfly/wildfly_9.x/standalone/configuration/config.properties

**Comment by rgarrigue** [comment]
I just tried replacing the HTML <style></style> content with [this CSS](https://gist.github.com/ryangray/1882525) I found randomly. That's okay for me now. 
But line wrapping would be a nice addition, maybe with a gray background or a border for code block.

**Comment by mike-ward** [comment]
I think it's a matter of interpretation here. Code blocks are wrapped in a `<pre>` element which are, well, preformatted.  In my code blocks, I format the code to fit comfortably on an A4 page. Unlike other forms of text (paragraphs, titles, etc) the format of the source matters (well matters more I suppose).
