### ISSUE TITLE
Portable Version Issues

### ISSUE THREAD

**Issue by RoyiAvital** [mike-ward/Markdown-Edit#152]
Hello,

The portable version has 2 issues:
- Once installed (Unzipped) into folder (Will be called Installation Folder) which is located on a drive which is different than the Main Drive (In the cases I checked, Main Drive is C:\ and the program installed on D:\) the program creates its `AppData` folder on 2 locations `<Installation Folder>\AppData` and `C:\Users\<User Name>\AppData\Local\MarkdownEdit\mde.exe_Url_<Random Signature>`.
- In both `AppData` folders above a settings file is created. While the program saves the settings the user changes in th UI into the settings file at `C:\Users\<User Name>\AppData\Local\MarkdownEdit\mde.exe_Url_<Random Signature>` on loading it loads the settings from the settings file in the Installation Folder.

Both issues above are bug and teh application expected to act differently:
- Create only 1 Settings folder (In Portable mode in the Installation Folder).
- Use and Save settings into the Settings File created in the Installation Folder.

Those issues were verified on 3 different computers all running Windows 10 64Bit.
For all 3 computers MDE installation is a clean one (Namely none of them has ever had MDE installed in Portable or Regular mode).

Thank You.

**Comment by mike-ward** [comment]
The `C:\Users\<User Name>\AppData\Local\MarkdownEdit\mde.exe_Url_<Random Signature>` file contains the last window position and a few other system specific settings. This is by design. Your welcome to disagree with my design decision but the implementation as it stands is not likely to change.

**Comment by RoyiAvital** [comment]
@mike-ward, The file in there is the same JSON settings file I have under `<Installation Folder>\AppData`.

Is that the decision choice?

I'm not talking about what you explained it is a necessity for .NET.
I'm talking about the Program Settings file (This is the cause settings are not saved).

Anyhow,
I can even share with you my computer (2-3 of them) to show you it happens over and over again.
I'm just a user who tries the report a bug.

I don't understand why I'm describing one thing and you response to other thing.

My question is simple, whys is the settings file is duplicated?
Why aren't settings being saved (The two are connected)?

Thank You.

**Comment by mike-ward** [comment]
The only file I have in `C:\Users\mike\AppData\Local\MarkdownEdit\mde.exe_Url_htckrcqzc5ek51ufz1skdztxdivvc020\1.27.0.0` is `user.config`

The files in my portable AppData folder

```
emoji_sprite.png
user_settings.json
user_template.json
custom_dictionary.txt
snippets.txt
```

I simply don't see duplicate files.

**Comment by shnbwmn** [comment]
I can confirm with @mike-ward. On my system, the two locations have files with different names and they hold different settings. This has been the case with both `1.26` and `1.27`.

**Comment by RoyiAvital** [comment]
@shnbwmn ,
Do you use the portable version?

Did you have it (the program) installed before?

Thank You.

**Comment by shnbwmn** [comment]
@RoyiAvital I use the portable version, and didn't have it installed before. But that doesn't matter, because I tested both versions in [Sandboxie](http://www.sandboxie.com/), which is independent of my computer's files.
