### ISSUE TITLE
Enforce CSS and add a black version, please?

### ISSUE THREAD

**Issue by sapioit** [mike-ward/Markdown-Edit#154]
Hi,

I am using a custom Windows 7 theme called [Plastic](http://msergt.deviantart.com/art/Plastic-331373530) and it changes the windows' colors. Could you, please, add custom CSS for the preview? And since you're at it, maybe add a toggle button for changing the colors from light to dark (maybe even have 2, one for the code and one for the preview).

**Comment by mike-ward** [comment]
A couple of things here.

- You can edit the template that MDE uses (F8)
- You can change themes (Ctrl+T)
