### ISSUE TITLE
[Bug] Multi line snippets (SnippetManager.cs)

### ISSUE THREAD

**Issue by veremenko-jav** [mike-ward/Markdown-Edit#157]
In SnippetManager.cs

Because you split with "count: 2" it will never hit the if-branch which allows multi line snippets.

```
var pair = line.Split(null, 2);
if (pair.Length == 2)
```

**Comment by mike-ward** [comment]
Multline snippets working here. Check the documentation at:

https://github.com/mike-ward/Markdown-Edit/wiki/Snippets

**Comment by veremenko-jav** [comment]
Thank you!
