### ISSUE TITLE
Not see the image link inserted 

### ISSUE THREAD

**Issue by waylau** [mike-ward/Markdown-Edit#16]
When I drag and drop a image to the Edit ，I can see the upload-progressbar works . When the uploading's  progress is 100% , progressbar disappearred, and I can't see the image link too.

**Comment by mike-ward** [comment]
There's been one other report of this. Probably a system specific issue. Hopefully, over time we will see a pattern. Please add info about your system to this issue.

**Comment by waylau** [comment]
@mike-ward 

OS 名称:          Microsoft Windows 7 旗舰版
OS 版本:          6.1.7601 Service Pack 1 Build 7601
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站

**Comment by mike-ward** [comment]
New release out (1.4.1). Give it a try to see if we can learn anything more about this issue.

**Comment by waylau** [comment]
@mike-ward  I tested 1.4.2 ,and I inserted a image , an error acourred as follow;

![001](https://cloud.githubusercontent.com/assets/3233966/7016573/9929d90e-dd19-11e4-97b4-b98202fe0b31.jpg)

My PC is  win 7.

**Comment by mike-ward** [comment]
According to Imgur, a 400 status code indicates the following:

> This error indicates that a required parameter is missing or a parameter has a value that is out of bounds or otherwise incorrect. This status code is also returned when image uploads fail due to images that are corrupt or do not meet the format requirements.

Does this occur with any image you try? It's possible I got a parameter wrong in the API, but given it's working elsewhere that seems less likely.

**Comment by waylau** [comment]
1. I am in China. Does Imgur support ?
2.I tried  any image format like png and jpg,but it doesn't work.

**Comment by mike-ward** [comment]
Can you access and upload images via the Imgur website?

**Comment by waylau** [comment]
@mike-ward  It's hard to visit  Imgur website in China. When I click "upload images"  button  try to upload a image to the website without sign in , the button acts nothing. When I try to register an account on Imgur , it's failed too .~

**Comment by mike-ward** [comment]
Are the other image uploading services in China that allow anonymous uploads?

**Comment by TongG** [comment]
Here: http://imgbox.com

**Comment by mike-ward** [comment]
I'm not seeing an API for imgbox.com

**Comment by TongG** [comment]
Well 😐neither am I

**Comment by mike-ward** [comment]
OK, then i'll revise my question. Are there any imaging hosting services in China that support an API with anonymous uploads?

**Comment by TongG** [comment]
@waylau 你平时翻墙吗？

**Comment by TongG** [comment]
Sadly, no. There are indeed several imaging hosting services in PRC that are not bad, but all of them don't support API with anonymous uploads. In fact, most of them don't support API at all.

**Comment by waylau** [comment]
@TongG  Not very often.It just depends.

**Comment by mike-ward** [comment]
Sounds like there's not much I can do then to resolve this issue on my end.

**Comment by TongG** [comment]
Yep, I can normally access Imgur because I bypassed the censorship from Chinese government by using proxy tools. Don't worry, it's not your app's problem.
