### ISSUE TITLE
GitHub emojis are not rendering in 1.28

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#161]
Possible bug in 1.28: something like `:question:` is no longer rendered as :question:.

**Comment by mike-ward** [comment]
Is there anything more you can add to this. I'm not seeing.

**Comment by borekb** [comment]
Hm, tried on another PC and cannot replicate the issue. May there be some caching problem?

**Comment by mike-ward** [comment]
Can't imagine how a cache would cause this. I updated the HTML template in 1.28 to use a dataUri of images. If you have an earlier template, it uses the external image file. The new template does not need the image file but I distribute it for backward compatibility.

**Comment by borekb** [comment]
Thanks, will look into the template, that might be it.

**Comment by mike-ward** [comment]
I try not to mess with the template for releases for this very reason. Sometimes it can't be avoided.
