### ISSUE TITLE
Quotation marks

### ISSUE THREAD

**Issue by ChuJung** [mike-ward/Markdown-Edit#164]
Can u add option to choose what quotation marks use by default – « » or “

**Comment by mike-ward** [comment]
Need more details here. Is this in the source or in the generated output?

**Comment by ChuJung** [comment]
Quotation marks in the source and generated output - ““. But i need in generated html output those marks «». So need option to shoose.

**Comment by mike-ward** [comment]
Currently, if you use [&rdquo;, &ldquo;] directly in the text and it will appear in the HTML. Unfortunately, there is no direct keyboard sequence to build these meaning you have to resort to some clever keyboard escape sequence. This is friction. However, I'm reluctant to change the meaning of `"`, even if it's an opt-in from the user.

You can add a snippet that inserts these curly quote characters in pairs (last line below). It would then be as simple as typing `"+tab`. 

```
now       $DATE("f")$ $END$
date      $DATE("d")$ $END$
time      $DATE("t")$ $END$

img       ![$alt_text$]($image_url$) $END$
link      [$link_text$]($link_url$) $END$

tm        &trade;
cp        &copy;
reg       &reg;

"         “$END$”
```
