### ISSUE TITLE
Dragging multiple image files inserts malformed markdown

### ISSUE THREAD

**Issue by cyotek** [mike-ward/Markdown-Edit#167]
If I drag a single image file into MDE, then I get a nice link. If I drag multiple files, then MDE malforms the links by inserting the markdown for the second image inside the markdown for the first and so on. This description makes no sense, so an example.

I drag two image files (both located in the same folder as my document) into MDE. The first is called `snaplines-custom-wm.gif`, and the second `snaplines-default-wm.gif`.

I would expect to get something like this

```markdown
![snaplines-custom-wm](snaplines-custom-wm.gif)
![snaplines-default-wm](snaplines-default-wm.gif)
```

But instead get

```markdown
![snap![snaplines-default-wm](snaplines-default-wm.gif)
lines-custom-wm](snaplines-custom-wm.gif)

```

(including an extra blank line that doesn't appear in the above block)

**Comment by mike-ward** [comment]
Oddly, I can't repro this. Maybe you can zip me a document and images that demonstrates the problem?

**Comment by cyotek** [comment]
Surprised you can't repro, it happens pretty much all the time for me. Doesn't seem to be related to any document or set of file names that I've observed.

Try this

```markdown
Title
=====

Some words
```

I stuck my cursor on the blank line, in case it was something to do with dragging before or after the cursor (doesn't seem to be). Then I tried dragging a pair of image files `test.png` and `palette.png` into the editor.

Didn't seem to matter where I dropped the files, invariably, they were munged into a corrupt form.

The only exception that seems solid was if I dropped the image files *past* the last line of the document - then they were inserted properly. Or, if the document was fully empty. Apart from those two conditions, malformed markdown was virtually always.

**Comment by mike-ward** [comment]
I was dropping past the end of the document. Explains it. Thanks.
