### ISSUE TITLE
tabs get converted into double spaces

### ISSUE THREAD

**Issue by englishextra** [mike-ward/Markdown-Edit#168]
Is that the intention? How is that tuned in user_settings.json?
![2016-07-27_223506](https://cloud.githubusercontent.com/assets/537127/17189577/bef3022e-544a-11e6-98e0-cc592e21b4e9.png)

**Comment by mike-ward** [comment]
That's by design. Press tab twice if you want 4.

**Comment by englishextra** [comment]
@mike-ward That's unfortunate. I remove every occurence of double spaces in all project files - that's CSS/JS/HTML/XML/JSON/MD, and for consistancy I use tabs for indention in MD files. So why would I have these four spaces indented code, which is horrible and inconsistent. I wouldn't be in a hurry to close the issue, because the design forces tu use other editor or IDE for editing MD files, and the Markdown Edit just for preview, which is weird and unhandy.
