### ISSUE TITLE
URLs automatically linkify

### ISSUE THREAD

**Issue by shariqansari** [mike-ward/Markdown-Edit#169]
If I write something like this in the edit pane:

`http://something.com`

then the URL in the preview pane automatically becomes a link. I realize that this is convenient, and probably intended behavior by the parser, but is there any way to turn this behavior off and just have the text appear as unlinkified text? Maybe an option that enables/disables this behavior? It would be nice to be able to write a URL without it automatically linking.

**Comment by mike-ward** [comment]
Autolinks are a feature of GitHub flavored markdown. To suppress:

1. Switch to the Commonmark engine
2. http\://something.com (place a backslash in front of the `:`

**Comment by klonos** [comment]
...or make the URL an inline code block (by wrapping it in `).
