### ISSUE TITLE
Don't support table preview

### ISSUE THREAD

**Issue by waylau** [mike-ward/Markdown-Edit#17]
when write a table in this Edit , it doesn't preview well

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

![123](https://cloud.githubusercontent.com/assets/3233966/6976468/ed9a6b6a-d9dc-11e4-9797-2664e5b5ddea.png)

**Comment by mike-ward** [comment]
CommonMark does not support tables.

**Comment by seperman** [comment]
@mike-ward if it is using pandoc, it should be able to preview tables, right?

**Comment by mike-ward** [comment]
Turn on the `GitHub Markdown` in the options.

**Comment by seperman** [comment]
cool. That worked.
