### ISSUE TITLE
Keyboard shortcut to nest a list item

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#170]
I often write nested lists and it would be useful if e.g. `Tab` would nest the list instead of inserting a Tab character.

Before pressing tab:

```
- First item
- |
```

After pressing tab:

```
- First item
    - |
```

**Comment by mike-ward** [comment]
Interesting idea. Don't think it would interfere with anything. I'll code something up to see how it goes..

**Comment by borekb** [comment]
Trying this out in 1.30 and it jumps two spaces – should be four to be safe in most MD implementations.

Other than that, it seems to be working nicely, handling both `Tab` and `Shift+Tab`. 👍

**Comment by mike-ward** [comment]
Tabs are always two spaces in MDE. Four might be safer but it's two everywhere else so I stuck to it for consistency.

**Comment by borekb** [comment]
Ah ok. Is this user-configurable? I'd set it to 4 spaces everywhere.

**Comment by mike-ward** [comment]
Nope, I've resisted this. It seems like such a trivial thing to double tap tab. Also, if someone set it to 8 they would get some behaviors they might not expect.

**Comment by borekb** [comment]
Fair enough.
