### ISSUE TITLE
[suggestion] highlight active line in both panes

### ISSUE THREAD

**Issue by EmperorXLII** [mike-ward/Markdown-Edit#174]
Currently, the edit pane shows a highlight background rectangle for the active line, where the caret is located.  It would be nice if the preview window also had a highlight for the same line, to make it easier to see what is currently being edited.

**Comment by mike-ward** [comment]
This is a hard problem. Looking for suggestions on how to do this. (character offsets won't work)

**Comment by EmperorXLII** [comment]
I don't have any knowledge of how the markdown parsing and translation happens, but as a general idea would it make sense to inject a special character, or nested html element, at the caret position in the document, then style the containing html element in the preview pane based on the presence of the caret object?

**Comment by mike-ward** [comment]
Still begs the question of what constitutes a line (where does it begin/end).

**Comment by EmperorXLII** [comment]
Ah, that's true.  I was thinking of "line" as a "logical element being edited", so if you had the caret anywhere in a multi-line quote, for example, the whole quote would be highlighted:
```
> if the caret is on either line,
> the whole block is highlighted

> but not other blocks
```
> **if the caret is on either line, the whole block is highlighted**

> but not other blocks

I could see there might be value in a more specific highlight scope (i.e. on line two, just the text `the whole block is highlighted` would get highlighted), but I had only been thinking of the simpler version.

**Comment by mike-ward** [comment]
I'm still not convinced this is a good idea. It changes the look of the document outside of the context of Markdown (why is the block bold or yellow, etc). It also runs against the grain of, "Minimal Distractions". I've not heard feedback from others which leads me to believe this is not something others want. I'm going to take a pass on this.
