### ISSUE TITLE
[suggestion] single-pane mode

### ISSUE THREAD

**Issue by EmperorXLII** [mike-ward/Markdown-Edit#175]
The edit pane already provides some rich highlight capabilities for markup (bold is **bold**, italics are _italic_, `# headers` are appropriately sized, lists/block quotes are shown in a different color, etc).

It seems like this is very close to being a full WYSIWYG experience, where the markup looks like a stylized version of the final document.  Personally, I would prefer such a single-pane editing experience, without the extra "true/final" preview (or only brining it up near the end, if I cared about the final appearance).

**Comment by cyotek** [comment]
It's already built in - press F12. Persists between sessions too.

**Comment by EmperorXLII** [comment]
Ah, thanks!  I had not realized that was an option.

I guess my only feedback is that I would like the edit experience to be even more preview-y :)  For example, a theme with more styling of lists/quotes, previews of images, etc.

**Comment by cyotek** [comment]
You're out of luck on the image front (not even sure if it's possible, i.e. if it's supported by AvalonEdit), but the themes that you access with `Ctrl+T` are found in `AppData\Local\MarkdownEdit\bin\Themes`. You could copy one of those and change it to suit your needs (assuming that folder isn't purged when upgrading) although from looking at them, you're limited in how much you can actually change.

**Comment by mike-ward** [comment]
Images on the editor-side strikes me as not Markdown. The point of Markdown (IMO) is to not hide formatting codes (like a traditional word processor). See Jeff Atwood's, https://blog.codinghorror.com/what-you-cant-see-you-cant-get/

**Comment by EmperorXLII** [comment]
@cyotek — Thanks, I had not looked at the `Themes` directory before.

@mike-ward — For images in particular, I was not suggesting the image _replace_ the markdown, but that the image appears _in addition to_ the markdown.  For example, if you enter:
```
![image](link to some image)
```
It would be nice if that showed up as:
```
┌───────────┐
│ the image │
└───────────┘
![image](link to some image)   // (maybe styled in a smaller font, like a source in an article)
```

**Comment by EmperorXLII** [comment]
I took a quick look at the themes.  Unfortunately, they seem to be limited to colors and font styles.  For a richer preview, I was hoping to have control over font size, line spacing, indentation, etc.  (As a trivial example: increase spacing before/after block quotes, and show them at a 0.8 relative font size.)

**Comment by mike-ward** [comment]
Again, the strength of Markdown is that it doesn't hide formatting controls. If the block quotes were indented, The user is left wondering if the indent is because it's in the source document or because of formatting.

The image becomes a non-editable area. It's confusing in that everything else is editable. Also, inline images would mess things up a bit.

There's always a balance with these things. Increasing the font size for H1 elements is even a bit questionable but I opted for it because it seemed pretty obvious what was happening.

There's a Markdown editor called Texts that operates in a more traditional WYSIWYG mode.

**Comment by EmperorXLII** [comment]
I agree there is a balance to be had; I'd just like to push it further to the "rich text" side of the scale :)

Based on the screenshots, the Texts editor is visually closer to what I would like.  For example, if the `Δ` were `>`, this is exactly the kind of styling I would like for a block quote:

![Tau](http://www.texts.io/samples/Tau.png)

In other words, I still want to see all of the markdown elements (<strong>`**bold**`</strong>, not **`bold`**).  But I want to see them in a way that makes them distinct and stand out (so that a quote doesn't just loo like "a blue paragraph" instead of "a gray paragraph").

**Comment by mike-ward** [comment]
MDE has what I think is a better feature. It can reformat documents to a standard format. It's as simple as pressing Alt+F

Block quotes get formatted as follows:
```
> We need a nice hero image for the main story in this issue. @Joshua Z
> can you please help source this? @Maggie W can help with touch ups
> once we finalize on the hero?
```

**Comment by the-reverend** [comment]
i wish single-pane mode had a previewer mode like marked2 does.

**Comment by mike-ward** [comment]
@the-reverend You mean like popup window vs. the tiled window?

**Comment by the-reverend** [comment]
if you have ever used marked2 on the mac, it watches the source file and just provides preview on changes. this way you can use the editor of your choice.

**Comment by mike-ward** [comment]
Markdown edit is an editor first. Preview only is not in scope.

**Comment by the-reverend** [comment]
sorry i mentioned it!

**Comment by mike-ward** [comment]
You're taking offense where none was offered. It's simply outside the scope of the project.

**Comment by the-reverend** [comment]
i'm just not used to your terse manner. i'm not a paying customer yet, so i'm adjusting expectations.

**Comment by mike-ward** [comment]
No worries...

**Comment by mike-ward** [comment]
I've changed the parameters for custom markdown editors. Instead of one setting, there are two; one for executable and one for the arguments. This permits the use of long file names. See the [wiki for details](https://github.com/mike-ward/Markdown-Edit/wiki/16.-Markdown-Engines)
