### ISSUE TITLE
Ö Standard windows shortcuts for diacritical marks

### ISSUE THREAD

**Issue by jackhistorynorton** [mike-ward/Markdown-Edit#178]
The standard windows shortcuts for diacritical marks -- ñ, á, ì -- all work in MDE. The ö only works if I set the keyboard to German. Is there any fix to this to make MDE have the same keyboard shortcuts as the Standard Windows shortcuts?

**Comment by mike-ward** [comment]
MDE doesn't do anything to short-circuit window keyboard shortcuts. What is the keyboard sequence and keyboard language where this occurs?

**Comment by jackhistorynorton** [comment]
Turns out, all Markdown editors (and text editors don't make the ö without Alt + 0246 . I checked Sublime, Notepad, and dillinger.io. The keystroke CTRL + shift + : which works in many MS products does not work in text editor. 

Sorry for taking you away from other issues. Just trying to figure out how to help a student get her name to appear in Markdown.
