### ISSUE TITLE
settings cannot scrolling

### ISSUE THREAD

**Issue by looly** [mike-ward/Markdown-Edit#18]
When i open settings, I can`t see bottom of setting.

My screen is 12inch

**Comment by mike-ward** [comment]
Could you send me a screen shot please?

**Comment by mike-ward** [comment]
For reference:

![unnamed](https://cloud.githubusercontent.com/assets/567927/7006409/ea460590-dc4e-11e4-9b30-27b0e61c9b20.png)

**Comment by mike-ward** [comment]
Are you using medium/larger display settings?

**Comment by looly** [comment]
My display setting is 1366 * 768

**Comment by mike-ward** [comment]
That's not what I meant. In the personalization settings, you can make all the screen elements larger.

![image](https://cloud.githubusercontent.com/assets/567927/7006588/63672700-dc50-11e4-9e1f-8982cde98684.png)

It's no longer important I added a scrollviewer to the settings dialog that will display a scrollbar if needed to see all the settings. Thanks for the bug report. I'll post this in a new release (probably 1.4.2.
