### ISSUE TITLE
directory installation

### ISSUE THREAD

**Issue by Li-An** [mike-ward/Markdown-Edit#183]
I discovered that from 1.28.1, the files are located in C:\Users\Myprofile\AppData\Local\MarkdownEdit\bin\mde.exe

Is it normal?

**Comment by mike-ward** [comment]
Indeed it is. By installing in the local folder, MDE does not require Admin privileges.

**Comment by Li-An** [comment]
OK. Good to know.

**Comment by Li-An** [comment]
Here again. I meet a problem with this installation directory. I use https://addons.mozilla.org/fr/firefox/addon/its-all-text/ extension that opens Markdown Edit when I edit a text (in WordPress). With the Program Files installation, the extension works (text in Markdown Edit is copied in the edit field in WP) but with AppData/Local, it does not wok (text in not transferred to WP). Just to say, I suppose I have to use the portable version.

**Comment by Li-An** [comment]
Just made another test: in fact, it seems the last version is not compatible at all with **It’s All Text**. Markdown Edit 1.28 and previous work (installed in Program Files).

**Comment by mike-ward** [comment]
MDE has always installed in the local app data folder so whatever has changed to cause the issue is not related to the installation location.

**Comment by Li-An** [comment]
I agree. It seems it’s more a "version" problem. I need to make a test with the install version of 1.28 version. Is it possible to get one ?

**Comment by mike-ward** [comment]
Yep, https://github.com/mike-ward/Markdown-Edit/releases

**Comment by mike-ward** [comment]
For what it's worth, I installed the "It's all Text" extension and it seems to work with the current version of MDE.

**Comment by Li-An** [comment]
OK, I’ve found my error: the extension needs saving and automatic saving was selected on one version of Markdown Edit and not on the other version. So I did not see that I needed to save the file to "send" it to the field managed by the extension.

Solved and thanks for your help - and sorry for losing your time in such way.

**Comment by mike-ward** [comment]
No worries...
