### ISSUE TITLE
Scrolling is choppy on preview pane, works well in source pane

### ISSUE THREAD

**Issue by sixhobbits** [mike-ward/Markdown-Edit#184]
If I scroll the preview pane using a touchpad, nothing happens until I end the scrolling motion (i.e. remove my fingers from the touchpad). Then the scroll 'catches up' and jumps to the correct end place in the document). Scrolling in the source pane works perfectly though.

I'm using a Dell xps 13 with Windows 10

**Comment by mike-ward** [comment]
This doesn't happen on my system. Maybe it's a touchpad driver issue?

**Comment by sixhobbits** [comment]
I just tried with a mouse as well, and scrolling with the scroll wheel is similar. I've attached an .mp4 of what I see -- perhaps it's intended?

[MARKDOWN EDIT - proposal.md 2016_09_03 4_07_49 PM.zip](https://github.com/mike-ward/Markdown-Edit/files/453416/MARKDOWN.EDIT.-.proposal.md.2016_09_03.4_07_49.PM.zip)

**Comment by mike-ward** [comment]
That's the normal scrolling behavior. MDE synchronizes scrolling at the block level to maintain accurate alignment. On large paragraphs as in your example that will cause a bit of jumping. It will also jump if you have large images.
