### ISSUE TITLE
Nested lists not rendered correctly when GFM enabled

### ISSUE THREAD

**Issue by daughtkom** [mike-ward/Markdown-Edit#186]
Nested lists are not rendered correctly when GFM is enabled.  See screenshots below and [attached sample Markdown file](https://github.com/mike-ward/Markdown-Edit/files/464550/list.sample.md.txt) to replicate the issue.

Using version 1.30.1.

-------

![broken with gfm](https://cloud.githubusercontent.com/assets/1824392/18397793/94afdcac-767e-11e6-96bf-a877b339d467.png)
![works without gfm](https://cloud.githubusercontent.com/assets/1824392/18397794/94b25414-767e-11e6-83ec-b30df94e9fdc.png)

**Comment by mike-ward** [comment]
This is one of those issues in Pandoc that will get resolved once CommonMark is finalized. In the meantime, you can indent 4 spaces to get the indented list.

**Comment by daughtkom** [comment]
Unfortunate, but understood...
