### ISSUE TITLE
Chinese garbled.

### ISSUE THREAD

**Issue by droidwolf** [mike-ward/Markdown-Edit#19]
Chinese garbled. Don't use the utf-8 encoding ？

**Comment by mike-ward** [comment]
Hi, I'm not sure I understand. Are you asking if the editor uses utf-8 encoding?

**Comment by droidwolf** [comment]
yes.Looking at your code (Editor.xaml.cs 371 lines) use File.ReadAllText to read files, ReadAllText is encoded using UTF-8.

**Comment by mike-ward** [comment]
I have other Chinese users who are not getting garbled documents. UT8 is usually considered the correct way to encode documents. It there a different encoding you require and if so, what is that encoding?

**Comment by droidwolf** [comment]
sorry!I made a mistake. I opened an ANSI file
