### ISSUE TITLE
Editor slows down dramatically after opening a certain file (see attachment)

### ISSUE THREAD

**Issue by t0lik** [mike-ward/Markdown-Edit#190]
Editor slows down dramatically when I start to change some words or scroll down in a certain file (see attachment).
All the entered characters appears in this document with a notable delay. Windows task manager does not show any strange behaviour of Markdown-Edit. 
I suppose this is a bug in spellchecker because of large line (over 7000 characters in one line, whole file size is just 10 KBytes). If I turn off the spellchecker then editor starts working as usual without any delays while entering characters or scrolling document.
[apA.zip](https://github.com/mike-ward/Markdown-Edit/files/478405/apA.zip)

**Comment by mike-ward** [comment]
Not seeing the issue here. Is this Windows 10 or 7? Anything else about the configuration that might help?

**Comment by t0lik** [comment]
Windows 10. Intel Core 2 Duo 2.92GHz, 8GB RAM. 
I don't have any problems with my PC performance. At the moment of Markdown-Edit checking my PC did not perform any CPU or RAM consuming tasks.

**Comment by t0lik** [comment]
Gotcha! Did you select Russian as spell-checker language?  In this case spell-checker assumes all the words incorrect.

**Comment by mike-ward** [comment]
Interesting. May have to do some threading here or at least make it cancelable.

**Comment by t0lik** [comment]
This is the most consuming place in Main thread while changing text in the editor:
![sloweditor](https://cloud.githubusercontent.com/assets/400628/18615912/db238574-7dba-11e6-9e8b-f3054494aebb.PNG)

**Comment by mike-ward** [comment]
As an experiment, I put a hard limit of 100 milliseconds on the renderer. Try the build below and see if that improves things.

http://expirebox.com/download/0577c19397ace5f9d3b69d90d021b2df.html

**Comment by t0lik** [comment]
A little better but still not acceptable for normal editing. Sorry!

I tried to solve this issue but unfortunately BackgroundGeometryBuilder requires the UI thread.

**Comment by mike-ward** [comment]
I'm thinking it might be better to tackle the issue from the other side and just limit the number of  misspelled words per paragraph (say 20).

**Comment by mike-ward** [comment]
I've limited the number of spelling errors to 20 per paragraph.
