### ISSUE TITLE
1.30.2 crashing after ~5 minutes

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#191]
Don't have much to add yet but MDE just crashed a couple of times after about 5 minutes of runtime. I've never seen that behavior before, will try to add more info as I find out more.

Nothing seems to be obviously wrong - in Task Manager, it consumes low CPU and about 80MB or RAM.

**Comment by borekb** [comment]
Just confirmed on an empty document with just `# Test` in it – I didn't save the document, just left MDE running for a couple of minutes and it crashed.

**Comment by mike-ward** [comment]
Tried this. Not seeing the issue. Can you send me your settings and template file? Maybe there's something in the configuration that triggers this.

**Comment by borekb** [comment]
There you go:

[Markdown Edit.zip](https://github.com/mike-ward/Markdown-Edit/files/479011/Markdown.Edit.zip)

**Comment by mike-ward** [comment]
OK, still no luck. I've built a version of MDE with a crash reporter in it. Hopefully, that will catch it.

http://expirebox.com/download/ebd90504462bc362b7fe18fae8495848.html

**Comment by mike-ward** [comment]
OH crap. I left the intentional exception in the code. Wait a few and build one that won't intentionally crash.

**Comment by borekb** [comment]
Got this:

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.NullReferenceException: Object reference not set to an instance of an object.

   at MarkdownEdit.Models.EditorLoadSave.LoadFile(Editor editor, String file, Boolean updateCursorPosition) in C:\Users\mike\GitHub\Markdown-Edit\src\MarkdownEdit\Models\EditorLoadSave.cs:line 34

   at MarkdownEdit.Controls.MainWindowViewModel.LoadCommandLineOrLastFile() in C:\Users\mike\GitHub\Markdown-Edit\src\MarkdownEdit\Controls\MainWindow.vm.cs:line 133

   at MarkdownEdit.Controls.MainWindowViewModel.<<OnFirstActivation>b__43_0>d.MoveNext() in C:\Users\mike\GitHub\Markdown-Edit\src\MarkdownEdit\Controls\MainWindow.vm.cs:line 115

   --- End of inner exception stack trace ---

---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.

   at MarkdownEdit.Models.EditorLoadSave.LoadFile(Editor editor, String file, Boolean updateCursorPosition) in C:\Users\mike\GitHub\Markdown-Edit\src\MarkdownEdit\Models\EditorLoadSave.cs:line 34

   at MarkdownEdit.Controls.MainWindowViewModel.LoadCommandLineOrLastFile() in C:\Users\mike\GitHub\Markdown-Edit\src\MarkdownEdit\Controls\MainWindow.vm.cs:line 133

   at MarkdownEdit.Controls.MainWindowViewModel.<<OnFirstActivation>b__43_0>d.MoveNext() in C:\Users\mike\GitHub\Markdown-Edit\src\MarkdownEdit\Controls\MainWindow.vm.cs:line 115<---
```

**Comment by mike-ward** [comment]
OK, took the intentional exception out. Got a little ahead of myself.

http://expirebox.com/download/adf3def5b72af4400247753a6f727f40.html

**Comment by borekb** [comment]
Hm, this version doesn't catch anything, I see the standard Windows crash dialog. Any logs I could look into?

**Comment by mike-ward** [comment]
The crash reporter is a "low" as I can get in an application when it comes to catching exceptions. The only other thing I can suggest is to attach a debugger and see if you can capture a stack trace.

**Comment by borekb** [comment]
Don't have skill for that :( Nevermind, I'll try other releases tomorrow.

**Comment by mike-ward** [comment]
Sorry, there's only so much I can do from this end. Keep me posted.

**Comment by borekb** [comment]
I'm now on another computer that does not have the latest cumulative Windows update (KB3189866) applied yet and all is fine. Will upgrade now to see whether the Update could be the issue.

**Comment by borekb** [comment]
All is OK on this PC, even after the Windows Update. I'll try to compare the machines to see what's different.

**Comment by mike-ward** [comment]
Also, check the drivers. I had a weird problem with my fan running all the time after the anniversary update. Updated my drivers and the problem went away.

**Comment by borekb** [comment]
I've tried just about everything now:

- Used settings from my good PC on my problematic PC.
- Tried rolling back to 1.30.1 which I know was working fine on this PC before.

Nothing helps. So strange..

**Comment by mike-ward** [comment]
Do you have any restore points saved?

**Comment by borekb** [comment]
Yes there's one before yesterday's KB3189866 update but it would take back a lot of my changes since then, I'll rather deal with the broken MDE. Are there some local caches or something I could try to purge?

**Comment by mike-ward** [comment]
None that I can think of. Maybe run CCleaner.

**Comment by borekb** [comment]
I've uninstalled KB3189866 and still the same issue.

Shame that MDE is not written in JavaScript / TypeScript, I could run it in the browser instead (and Linux guys would get it via Electron as well, #188) :)

**Comment by borekb** [comment]
Happy to report that I managed to get rid of the issue. I just uninstalled MDE, went to `%AppData%\Local\MarkdownEdit` and deleted everything there (folders like `mde.exe_Url_50vhyrglrhvxwx52lohg51rppoayw2u3` etc.). After installing MDE again, all is OK.

**Comment by borekb** [comment]
Fuck, as I submitted this, MDE crashed again :( It was after 10-15 minutes though so that gives me enough time to write most of the Markdown I need :)

No, just kidding, this Windows UWP / XAML / WPF platform is ridiculous.

**Comment by borekb** [comment]
It occurred to me that the preview (which is probably something like embedded IE) might be causing the crash so I've hidden it. When MDE is in text-only mode, it seems not to crash. Fingers crossed. 🤞

**Comment by borekb** [comment]
No it didn't help. The difference seems to be that when the window is minimized, MDE will not crash but as soon as it's a normal or maximized window, it will crash in a couple of minutes.

(BTW @mike-ward I hope these comments don't bother you. I try to collect as much information as possible but the issue is closed and I don't expect any replies :) ).

**Comment by mike-ward** [comment]
Information = good 😄 

This still sounds like a driver issue to me.

**Comment by borekb** [comment]
Graphics driver? I don't have similar issues with other apps but maybe most of them are not XAML / WPF.

**Comment by mike-ward** [comment]
What makes you think it's WPF?

**Comment by borekb** [comment]
That's about the only differentiator between MDE and other apps on my system. When I used to use Visual Studio (which also contains parts written in WPF), it used to be one of the very few apps that crashed on my system as well, although in that case it might have also been caused by the sheer complexity of that monster.

**Comment by mike-ward** [comment]
MDE hosts the IE control which is more likely cause problems than WPF (So does VS). Have you tried resetting your IE settings?
