### ISSUE TITLE
Dialog Find & Replace too narrow with translated interface

### ISSUE THREAD

**Issue by t0lik** [mike-ward/Markdown-Edit#192]
Please see this screenshot: 
![find_and_replace](https://cloud.githubusercontent.com/assets/400628/18627336/16c06900-7e63-11e6-99db-02346133677e.png)

I suppose that buttons and the window itself have to have autosize limited by some sensible limit.

**Comment by mike-ward** [comment]
Finally, a bug I know how to fix 😄
