### ISSUE TITLE
Add en/em dashes support

### ISSUE THREAD

**Issue by t0lik** [mike-ward/Markdown-Edit#195]
I didn't find any appropriate way to insert quickly en or em dash to an editor text. No hotkey and no word-style conversion ("--" -> "—") work. Am I missing something?

**Comment by mike-ward** [comment]
Markdown doesn't support this. However, you could put use a snippet to do this.

**Comment by t0lik** [comment]
I just have tried snippets. It works for dashes. The only offer is to optionally support activation of some snippets on Space key, not Tab. This will be ideal! )))

**Comment by mike-ward** [comment]
Space strikes me as a bit too intrusive.

**Comment by t0lik** [comment]
Ok. What about to just include the snippet "- —" in a standard snippet list?

**Comment by mike-ward** [comment]
I would suggest "-- —". When composing lists I suspect the single "-<TAB>" might result in an unwanted surprise.

**Comment by t0lik** [comment]
It's a deal!
