### ISSUE TITLE
Visible Windows taskbar in fullscreen mode

### ISSUE THREAD

**Issue by t0lik** [mike-ward/Markdown-Edit#196]
After updating Windows 10 to version 1607 fullscreen mode was broken (see attached screenshot).
![wrong fullscreen mode](https://cloud.githubusercontent.com/assets/400628/19021750/2108dc30-88d1-11e6-8735-f6a6557866b5.png)

**Comment by mike-ward** [comment]
I plan on releasing a patch today.

**Comment by t0lik** [comment]
This fix does not work properly. 
Steps to reproduce the issue:
1. Open the app in fullscreen mode
2. Minimize tha app
3. Restore the app window back (for instance, by Alt+Tab). 
4. Taskbar apears in front of the app again.

Workaround: 
1. Click to the button (I don't know its name in English, maybe "Normal window") between "Miminize" and "Close" in the app window header.
2. Click to the button "Maximize" between "Miminize" and "Close" in the app window header.

**Comment by mike-ward** [comment]
Probably something Mahapps will have to fix. Can you log an issue there?

**Comment by punker76** [comment]
@mike-ward @t0lik I'll try to fix another @Microsoft bug...

**Comment by mike-ward** [comment]
@punker76 Thanks for doing this. Fiddling with the window chrome in windows is always vexing.
