### ISSUE TITLE
Provide a smoother update/upgrade experience

### ISSUE THREAD

**Issue by UweKeim** [mike-ward/Markdown-Edit#198]
The current setup process is hard for me as a user:
1. (Accidentially) See the upgrade icon.
2. Click it.
3. Browser lands on a generic website.
4. Have to finde download button.
5. Have go to GitHub releases.
6. Have to finde download button, again.
7. Download MSI package.
8. Click it.
9. Have Windows SmartScreen prevent execution (missing Authenticode signature).
10. Click "More information"
11. Click "Execute" anyway. Wizard starts.
12. Click "I accept".
13. Click "Install".
14. Wait.
15. Click "Finish".
16. Click the Desktop/Task Bar icon.

Instead I suggest an update mechanism that is as simple as Google Chrome or other Electron applications like e.g. Atom.io or the GitHub Windows client.

They all use [Squirrel](https://github.com/Squirrel/Squirrel.Windows).

Would be _such_ a great relieve to me.

**Comment by mike-ward** [comment]
I've looked at Squirrel. It's kind of a mess in my opinion. Same goes for One-Click. 

The current process is not nearly as burdensome as you make it out to be. Yeah, it's a few more clicks but it takes less than a minute to update the product. 

You do make a valid point about going back to  http://markdownedit.com when clicking the update button. I'll change MDE to go to the latest GitHub release. That still means you have to pick the installer from the list of release artifacts and download it. Not ideal perhaps but really not that hard either. 

I always supply update notes in my releases. I think it's important to inform users what's in the update and if there are breaking changes.

I have considered releasing a UWP version of the app using the DesktopAppConverter bridge from Microsoft. This would allow the product to be hosted in the App Store and provide the automatic update options you have described.

Thanks for the feedback.

**Comment by UweKeim** [comment]
Thanks, Mike. Actually I skip most of the updates because of the update process. And it's not that "one minute", it is that fact that I have to put all my concentration away from my daily business tasks (developing code) and get a into a completely different "doing some update" mindset.

Thanks for your great tool and your feedback!
