### ISSUE TITLE
Syntex highlighing of comments glitches

### ISSUE THREAD

**Issue by ArcoMul** [mike-ward/Markdown-Edit#20]
I'm using markdown comments quite extensively, and I noted some syntax highlighting issues. Pretty sure they are related.

These images should make clear what's up:

![image](https://cloud.githubusercontent.com/assets/1388162/7532793/6fec8cfc-f56b-11e4-923e-93b19b14d714.png)

![image](https://cloud.githubusercontent.com/assets/1388162/7532801/76bffd48-f56b-11e4-8360-e00339a4bd96.png)

(Great editor by the way, thanks a lot!)

**Comment by mike-ward** [comment]
I'll investigate. Thanks for bug report.

**Comment by mike-ward** [comment]
Oddly, this is not a bug. From the Commonmark spec:

> An HTML block begins with an HTML block tag, HTML comment, processing instruction, declaration, or CDATA section. It ends when a blank line or the end of the input is encountered.
