### ISSUE TITLE
The characters "Res:" break rendering for some unknown reason

### ISSUE THREAD

**Issue by nonplayer** [mike-ward/Markdown-Edit#209]
I can't for the life of me figure out why, but the specific four characters "Res:" in sequence, breaks certain markdown rendering in both the editor and the preview. It breaks the rendering of the current line _and_ the line immediately following. Paste this into the editor to see what I'm talking about:

```
**Red:**  
**Anything:**  
**Res:**  
**Anything:**  
**Red:**  
**Anything:**  
**Res:**  
**Anything:**   
**Red:**  
**Anything:**  
**Rest:**  
**Anything:**   
**Red:**  
**Anything:**  
**Resource:**  
**Anything:**   
```

Almost any word starting with "Res" does it, as shown in the example above.

An escaping slash in front of the colon fixes the rendering of the boldface font, but the escape slash is also still printed as well, which is an unwanted result.

This is unfortunate, as I'm writing out a list of definitions inside my text, and two of them are "Resource:" and "Res:" and, well, both words break the rendering.

**Comment by nonplayer** [comment]
Here's a screenshot of what I'm talking about:

![capture](https://cloud.githubusercontent.com/assets/5161177/20465197/887345e8-af0c-11e6-8ed6-eabf0481fd1a.JPG)

**Comment by mike-ward** [comment]
Pandoc's GitHub rendering (Markdown Edit uses Pandoc to render GitHub markdown) is at odds with the GitHub and CommonMark in a few places. This is one of them. If you switch to the CmmonMark rendering (unselect Github in settings) you'll see that it renders correctly. Pandoc is aware of the issue and it is my understanding that when the CommonMark spec if finalized, this will be fixed.

**Comment by nonplayer** [comment]
Ah that fixed it. Thanks!

**Comment by nonplayer** [comment]
Ack, so now I'm realizing that switching off the GitHub rendering completely breaks Tables. They just don't render at all. Seems CommonMark just doesn't support them.

Unfortunately, MarkdownEdit is currently the only Markdown app I have that suffers from this issue. Using both Multimarkdown+Github, Pandoc Multimarkdown+Github, and simply Pandoc+Github in a few others testing it out, I'm unable to reproduce the original "res" rendering bug from above in any other editor.

So now I'm stuck, it seems. If I want to keep using MarkdownEdit, I have to either break rendering with the simplest of three-letter combinations (I still don't understand what the heck is happening there), or I have to just not use tables. And neither is a good option, they both break my work flow, to the point that I'm once again forced to use a different app to render and print, and that defeats the purpose of using this one in the first place.

**Comment by mike-ward** [comment]
It's an edge case in Pandoc.
