### ISSUE TITLE
Request: Line break option

### ISSUE THREAD

**Issue by c-lipka** [mike-ward/Markdown-Edit#215]
There seem to be two different schools among Markdown implementations how to deal with simple line breaks: While some categorically do render them as line breaks, others only do so if they are preceded by two blanks.

I definitely favour the latter variant, as it allows for Markdown documents that can easily be viewed and further edited with the most simple of ASCII text editors, without having to struggle with overly long lines.

Please give us a switch to choose this behaviour.

**Comment by mike-ward** [comment]
The behavior you speak of is dependent on the markdown processor. GitHub uses hard line breaks. CommonMark does not. The guidelines are specific and rigid about this behavior and can't really see a reason to vary.

**Comment by c-lipka** [comment]
Sorry, my bad; I hadn't expected this behaviour to pe part of what's hiding behind the "GitHub" switch.

BTW, are there any plans to implement a dedicated Doxygen mode?

**Comment by mike-ward** [comment]
Rather than discuss Doxygen here, open a new issue. A use-case helps in deciding on what behavior is desired.
