### ISSUE TITLE
Request: "Format on save" options

### ISSUE THREAD

**Issue by c-lipka** [mike-ward/Markdown-Edit#216]
I think I like the "format on save" option in general, but what I don't like is that it uses the "wrong" style for italics:

I love my text decoration "weight" in ASCII to most closely reflect the "weight" in formatted view; to that end, I think bold text should be formatted using the "heavy" asterisk notation, while italics text should be formatted using the "light" underscore notation.

Please give us a switch to choose.

Also, I prefer my list bullets/numbers to be indented a bit so that I only have a single blank between the bullet or number and the actual text. I'd like a switch for that as well.

**Comment by mike-ward** [comment]
You can change the how bold and italic text is rendered in the settings (F9).

The list indentation is controlled by Pandoc. Keep in mind that indentation can effect document rendering which I'm guessing is why Pandoc does it the way it does.

**Comment by c-lipka** [comment]
You've obviously misunderstood me: I don't want to change the way italic text is rendered in the HTML preview, nor how it is rendered in the ASCII view. I'm happy with that. But I'm not happy with how it looks in _raw ASCII_ (as e.g. viewed in an external editor) after formatting: I want format to turn italics into `_foo_` rather than `*foo*`.

**Comment by mike-ward** [comment]
I see now. I use Pandoc to format documents. I don't believe there is a switch to override this behavior.
