### ISSUE TITLE
Going to full screen activates always-on-top

### ISSUE THREAD

**Issue by bladewolf55** [mike-ward/Markdown-Edit#221]
**Type: Bug**
Expanding the editor window to full screen, either through the expand control or F11, activates always-on-top mode. When the window is returned to normal, always-on-top is not disabled.

**Steps**
1. Open Markdown Edit (ME) in front of another window.
2. Verify other window can be brought in front.
3. F11 to expand ME to full screen.
4. F11 again to return to window view.
5. Other window cannot be brought in front of ME.

Version: 1.31
Platform: Windows 10 Pro

**Comment by mike-ward** [comment]
MahApps has committed to fixing this issue in a future release.

**Comment by bladewolf55** [comment]
Thank you!

**Comment by bladewolf55** [comment]
Thanks you!
