### ISSUE TITLE
~~stroke~~ does not pasting correctly into the Office Outlook/Word

### ISSUE THREAD

**Issue by veremenko-jav** [mike-ward/Markdown-Edit#232]
~~stroke~~ does not pasting correctly into the Office Outlook/Word (tested 2016 edition)
![stroke](https://cloud.githubusercontent.com/assets/4127660/22090723/d5e333e2-ddb0-11e6-9fde-4bd959b2bf89.png)

**Comment by mike-ward** [comment]
Um... Works here with Word 2010.

**Comment by veremenko-jav** [comment]
How can I test it from you? Any clipboard viewer? Any specific type of clipboard?

**Comment by mike-ward** [comment]
It's just plain text in the clipboard. Not sure why one version of Word would behave differently than another on this. Have you tried pasting `~~strike~~` from  a different program like notepad>

**Comment by veremenko-jav** [comment]
I'm sorry, Mike. You misunderstood me. I copy from the right HTML panel, not the left.
If I have
```
~~strike~~
<strike>strike</strike>
```
And copy paste HTML into the Word, `~~strike~~` id not pasting but `<strike>strike</strike>` does.

**Comment by mike-ward** [comment]
That's browser control functionality. Not really something I can fix.

**Comment by veremenko-jav** [comment]
No, that's how MarkdownEdit renders it

```html
<!--~~strike~~-->
<div id="content"><p><del>strike</del><br>
<!--<strike>strike</strike>-->
<strike>strike</strike></p>
```

**Comment by mike-ward** [comment]
Sorry but just can't make sense of what you are saying.

**Comment by veremenko-jav** [comment]
Please see schreenshot
![strike](https://cloud.githubusercontent.com/assets/4127660/22161518/e695f410-df07-11e6-8233-2833d8492dcf.png)

**Comment by mike-ward** [comment]
Sorry but `<del>` is what the markdown converter converts to. Not in my control.
