### ISSUE TITLE
The window covers the taskbar when maximized

### ISSUE THREAD

**Issue by franzalex** [mike-ward/Markdown-Edit#247]
Exactly as the title says.
When the window is maximized, it covers the taskbar even when the taskbar is set to remain on top of other windows.

Kindly remedy this or, at least, add a setting to keep it from covering the taskbar.

**Comment by GwenaelPellenArkeup** [comment]
It's metro windows issue...

You can show taskbar with WIN + T

**Comment by mike-ward** [comment]
Don't think I ever noticed that before...

The rewrite doesn't do this (so far).

**Comment by GwenaelPellenArkeup** [comment]
Well, i found \o/

ligne 17 in MainWindow.xaml
 IgnoreTaskbarOnMaximize="{Binding Path=IgnoreTaskbarOnMaximize, Source={x:Static local:App.UserSettings}}"

In application, in advanced setting:
edit setting
from:
  "IgnoreTaskbarOnMaximize": true,
to
  "IgnoreTaskbarOnMaximize": false,

**Comment by franzalex** [comment]
Great! Thanks @GwenaelPellenArkeup :-)

I have fixed my application now. Going forward, I think this setting should be `false` by default or it should be brought into the settings panel to make it more visible and easily changeable.

**Comment by mike-ward** [comment]
Explains why the rewrite doesn't do it. Thanks...
