### ISSUE TITLE
Crash on windows 7

### ISSUE THREAD

**Issue by cryptohazard** [mike-ward/Markdown-Edit#252]
Hi,

I have been using your program for a while. Lately I run into an error and I cannot load the program any more. This might be because I am on a professional PC and I cannot run the installation any more.

So below the crash report

---------------------------

---------------------------
MarkdownEdit Crash Report

Date: 2018-02-20 10:36:04Z

Version: 1.33

-----------------------------------------------------------------

*** Pressing Ctrl+C will copy the contents of this dialog ***

*** Email to: mike@mike-ward.net ***

-----------------------------------------------------------------

Operation System Information

-----------------------------------------------------------------

Windows 7 Enterprise

Service Pack: Service Pack 1

Exception

-----------------------------------------------------------------

System.Windows.Markup.XamlParseException: La valeur fournie sur 'System.Windows.Markup.StaticExtension' a levé une exception. ---> System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.TypeInitializationException: Une exception a été levée par l'initialiseur de type pour 'System.Windows.Media.Fonts'. ---> System.IO.FileFormatException: No FontFamily element found in FontFamilyCollection that matches current OS or greater: Windows7SP1 ---> System.IO.FileFormatException: No FontFamily element found in FontFamilyCollection that matches current OS or greater: Windows7SP1

   à MS.Internal.FontFace.CompositeFontParser.Fail(String message, Exception innerException)

   à MS.Internal.FontFace.CompositeFontParser.ParseFontFamilyCollectionElement()

   à MS.Internal.FontFace.CompositeFontParser..ctor(Stream fileStream)

   --- Fin de la trace de la pile d'exception interne ---

   à MS.Internal.FontFace.CompositeFontParser.Fail(String message, Exception innerException)

   à MS.Internal.FontFace.CompositeFontParser..ctor(Stream fileStream)

   à MS.Internal.FontCache.FamilyCollection.SystemCompositeFonts.GetCompositeFontFamilyAtIndex(Int32 index)

   à MS.Internal.FontCache.FamilyCollection.GetFontFamilies(Uri fontFamilyBaseUri, String fontFamilyLocationReference)

   à System.Windows.Media.Fonts.CreateFamilyCollection(Uri fontLocation, Uri fontFamilyBaseUri, String fontFamilyLocationReference)

   à System.Windows.Media.Fonts..cctor()

   --- Fin de la trace de la pile d'exception interne ---

   à System.Windows.Media.Fonts.get_SystemFontFamilies()

   --- Fin de la trace de la pile d'exception interne ---

   à System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   à System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

   à System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   à System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)

   à System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)

   à System.Windows.Markup.StaticExtension.GetFieldOrPropertyValue(Type type, String name, Object& value)

   à System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)

   à MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)

   --- Fin de la trace de la pile d'exception interne ---

   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)

   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)

   à System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)

   à MarkdownEdit.Controls.MainWindow.InitializeComponent() dans C:\Users\mike\GitHub\Markdown-Edit\src\MarkdownEdit\Controls\MainWindow.xaml:ligne 1

   à MarkdownEdit.Controls.MainWindow..ctor(ISpellCheckProvider spellCheckProvider, ISnippetManager snippetManager) dans C:\Users\mike\GitHub\Markdown-Edit\src\MarkdownEdit\Controls\MainWindow.xaml.cs:ligne 26

   à MarkdownEdit.App.OnStartup(Object sender, StartupEventArgs ea) dans C:\Users\mike\GitHub\Markdown-Edit\src\MarkdownEdit\App.xaml.cs:ligne 58

   à System.Windows.Application.OnStartup(StartupEventArgs e)

   à System.Windows.Application.<.ctor>b__1_0(Object unused)

   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---------------------------
OK   
---------------------------

**Comment by mike-ward** [comment]
Just looking at the stack trace, it appears that there are some system font's missing on your system.

**Comment by cryptohazard** [comment]
Any idea which one? I could try to download them manually and see if it gets fixed.

**Comment by mike-ward** [comment]
See #54

**Comment by cryptohazard** [comment]
Just tried. It didn't fix my issue :-(

**Comment by zonky2** [comment]
I worked with the editor for a few days but now I can't start the program anymore.

Win7 64 Ultimate

**Comment by zonky2** [comment]
closed? why?

**Comment by mike-ward** [comment]
I don't support Windows 7.
