### ISSUE TITLE
Script Error on opening mde 

### ISSUE THREAD

**Issue by sas-3** [mike-ward/Markdown-Edit#258]
Line: 1232
Error: Object doesn´t support property or method 'attachEvent'

![error](https://user-images.githubusercontent.com/38133484/46480695-084bd280-c7f2-11e8-9027-d4116841c709.png)

thx sas

**Comment by mike-ward** [comment]
Yep, a pull request is causing issues. Pushed a new release (1.35). You'll also have to go to `%USER%\AppData\Roaming\Markdown Edit` and delete the `user_template.html` file.
