### ISSUE TITLE
Crash when pasting url

### ISSUE THREAD

**Issue by Andreone** [mike-ward/Markdown-Edit#26]
Trying to paste something like *https://github.com* crashes MarkdownEdit.
Tested version: 1.8.1.

**Comment by mike-ward** [comment]
Um.... I'm not seeing that here using drag and drop or Ctrl+V. Is there another way to repro this?

**Comment by Andreone** [comment]
I retested this morning and still crashes. I inspected the mini dump and the error is:

>An unhandled exception of type 'System.Runtime.InteropServices.COMException' occurred in mscorlib.dll
Additional information: OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))

And the callstack is:

> 	[Managed to Native Transition]
>	mscorlib.dll!System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(int errorCode, System.IntPtr errorInfo)	Unknown
 	PresentationCore.dll!System.Windows.Clipboard.Flush()	Unknown
 	mde.exe!MarkdownEdit.Controls.Editor.OnPaste(object sender, System.Windows.DataObjectPastingEventArgs pasteEventArgs)	Unknown
 	PresentationCore.dll!System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate handler, object target)	Unknown
 	PresentationCore.dll!System.Windows.EventRoute.InvokeHandlersImpl(object source, System.Windows.RoutedEventArgs args, bool reRaised)	Unknown
...

I'm on Windows 7 Pro 64bits.

**Comment by mike-ward** [comment]
So is it drag and drop or Ctrl+V. I need some steps to repro this.

**Comment by Andreone** [comment]
Sorry. It was using CTRL+V.

**Comment by mike-ward** [comment]
The stack trace indicates that Markdown Edit can't open the clipboard. Not sure what would restrict MDE from opening the clipboard. Copy/Paste is not going to work if access to the clipboard is limited.

**Comment by Andreone** [comment]
When the clipboard contains regular text, CTRL+V works as expected.

**Comment by mike-ward** [comment]
What app are you pasting from?

**Comment by Andreone** [comment]
From MDE itself. And I disabled my clipboard manager (the Ditto app).

**Comment by mike-ward** [comment]
Still can't reproduce this error.
