### ISSUE TITLE
Error window on launch.

### ISSUE THREAD

**Issue by HonzaSTECH** [mike-ward/Markdown-Edit#269]
Everytime I launch Markdown Edit (version 1.35), this dialog pops out: 
![image](https://user-images.githubusercontent.com/19894267/75094348-8301c300-558a-11ea-8570-f7ec3b1cf5ab.png)

The message says in Czech this:
_**Script error**
⚠ An error occured in a script on this page.
Line: 0
Character: 0
Error: Script error
Code: 0
URL: http://markdownedit.com/assets/js/mathjax-scripts.js
Do you want to continue launching scripts on this page?
[Yes][No]_

No matter if I click Yes or No, this error is displayed again the next time I launch the program. It doesn't make it unusable (I haven't noticed any problems with the program), it is just a bit annoying.

Reinstalling didn't fix the issue.

I am using Windows 10 64bit.

**Comment by mike-ward** [comment]
Well, something in the mathjax-script is causing the embedded browser to throw errors.. Probably some recent change in .NET framework update. You could edit the template (see settings) and remove the mathjax scirpt.

**Comment by haverholm** [comment]
Well, yes -- and markdownedit.com, where the script should be located, appears to be defunct...

**Comment by HonzaSTECH** [comment]
Just letting you know, I don't think I changed something, but the window stopped appearing.
