### ISSUE TITLE
Crash in settings

### ISSUE THREAD

**Issue by Virtlink** [mike-ward/Markdown-Edit#28]
Hi, I just installed your editor (and it looks great!) but I found an issue: the program crashes in the settings screen.

### To reproduce

1. Open a file using the editor.
2. Click the Settings gear icon.
3. Change the font size using the +/- buttons.
4. Scroll down and click the `Settings` button. This opens Notepad.
5. Close Notepad.
6. Click the arrow next to the word Settings to close the settings pane.
7. Click anywhere in the preview area.
8. Now the program crashes.

### Additional information
I've installed it using Chocolatey on Windows 8.1. This is the information I get (in Dutch):

	Probleemhandtekening:
	  Gebeurtenisnaam van probleem:	CLR20r3
	  Probleemhandtekening 01:	mde.exe
	  Probleemhandtekening 02:	1.8.2.0
	  Probleemhandtekening 03:	557da292
	  Probleemhandtekening 04:	mde
	  Probleemhandtekening 05:	1.8.2.0
	  Probleemhandtekening 06:	557da292
	  Probleemhandtekening 07:	123
	  Probleemhandtekening 08:	15
	  Probleemhandtekening 09:	System.InvalidOperationException
	  Versie van besturingssysteem:	6.3.9600.2.0.0.256.4
	  Landinstelling-id:	1043
	  Aanvullende informatie 1:	506b
	  Aanvullende informatie 2:	506b05d5f26ecb1a6532e46dab57c94c
	  Aanvullende informatie 3:	7398
	  Aanvullende informatie 4:	73989f83612b9c72982303e2c8b92311

**Comment by mike-ward** [comment]
Hi,

Thanks for the bug report. I'm not seeing this issue. Can anyone else reproduce?

**Comment by Virtlink** [comment]
I'm unable to debug this as I'm not using VS2015, but I noticed you haven't enabled NuGet package restore, causing all packages to be missing when I open the project.

**Comment by mike-ward** [comment]
Not a fan of package restore. Causes too many other problems (for me). The build.cmd should update the packages.

VS2015 is free :)

**Comment by Virtlink** [comment]
I installed VS2015 but NuGet is crashing it constantly to the point it wasn't usable. It's strange that you can't reproduce this bug since I can reproduce it consistently on my computer. I believe it has to do something with the font-size having been changed but not updated in the settings file that's shown in Notepad when the `Settings` button is clicked, but I'm not sure.

**Comment by Virtlink** [comment]
I've since installed the VS 2015 final release, and I can't reproduce the crash any more, neither in the original Chocolatey installation (1.8.2.0) nor the source I built myself. Therefore this issue can be closed.
