### ISSUE TITLE
Embedded IE is not using standards mode

### ISSUE THREAD

**Issue by adamzuckerman** [mike-ward/Markdown-Edit#31]
There is a known issue when using the embedded IE web browser in a desktop application.  When you embed a browser, IE uses 7 quirks mode to display the pages.  To change the output to something more modern (and standards compliant), you will need to update a registry setting.

The best example I have found of how to do this can be found on [CodeProject](http://www.codeproject.com/Articles/793687/Configuring-the-emulation-mode-of-an-Internet-Expl).

**Comment by mike-ward** [comment]
This can be controlled with a meta tag in the template. The default template uses:

`<meta http-equiv="X-UA-Compatible" content="IE=9">`
