### ISSUE TITLE
Refresh markdown file

### ISSUE THREAD

**Issue by sualeh** [mike-ward/Markdown-Edit#33]
Please refresh the markdown file when the application receives focus, since it may have changed. I save my markdown files in Dropbox, as well as keep the file open in Markdown-Edit. I would like to see the latest updates when Dropbox refreshes the file. Thanks.

**Comment by mike-ward** [comment]
The typical pattern I've seen is to wire a refresh it to a menu item and the F5 key. Will that work? I'm leary of automatically updating the document without user action.

**Comment by sualeh** [comment]
I think F5 would work for me. A menu item would help make it obvious to a new user too. So, yes, both a menu item and F5. Thanks.

**Comment by mike-ward** [comment]
Added revert command and wired to F5. Available in next release.

**Comment by sualeh** [comment]
Thanks. How long do you estimate for the next release?
