### ISSUE TITLE
Scrollbars do not show in Windows 10

### ISSUE THREAD

**Issue by sualeh** [mike-ward/Markdown-Edit#35]
The HTML preview does not have any scrollbars in Windows 10. I tried various things, including using a CSS scale transform. I was able to see the scrollbars with an extreme scale-down. My guess is that the embedded IE is somehow not reporting its visible area correctly.

**Comment by mike-ward** [comment]
I'm running it on three different Win 10 laptops and not seeing this issue.

**Comment by sualeh** [comment]
Please let me know if you need any debug information.

**Comment by mike-ward** [comment]
I'll leave this issue open. I'm curious if anyone else is seeing this.

**Comment by sualeh** [comment]
Ok, I figured out what was happening. If you go to:

> Customize your display -> Change the size of text, apps and other items -> 125%

The HTML preview does not have any scrollbars in Windows 10. If you zoom to 100%, everything works. Windows 10 recommends 125%, so I do not see scrollbars. Please can you fix this issue? Thanks.

**Comment by mike-ward** [comment]
Sorry, still can repro this. At %125 scrollbars appear and work.

Github issues support uploading images. Create a new response to this issue and then drag and drop the image. Perhaps if I see a screenshot I can puzzle out what's happening.

**Comment by sualeh** [comment]
![screenshot 2015-11-04 20 10 51](https://github-cloud.s3.amazonaws.com/assets%2F58572%2F10957221%2F455b3e9a-8330-11e5-85ee-f3e5babf2715.png)
![screenshot 2015-11-03 20 29 33](https://github-cloud.s3.amazonaws.com/assets%2F58572%2F10957219%2F45558734-8330-11e5-9b25-9df7311dd3a5.png)
![screenshot 2015-11-03 20 46 20](https://github-cloud.s3.amazonaws.com/assets%2F58572%2F10957220%2F4555eab2-8330-11e5-8e59-b2ac6c90febc.png)
