### ISSUE TITLE
Add snippet for clipboard content

### ISSUE THREAD

**Issue by Li-An** [mike-ward/Markdown-Edit#37]
Hello,
I suppose it's better to put the requests here rather than in comments...

I would like a $CLIPBOARD$ snippet to manage the content of the clipboard to paste in different places the same content. I can manage it with underscore system but it's not the quickest way for my use. Tell me if it's possible or not.
Thanks.

**Comment by mike-ward** [comment]
Sounds like a nice addition. I'll add it to the enhancements list.

**Comment by Li-An** [comment]
Thanks again.

**Comment by mike-ward** [comment]
Added. Will appear in version 1.11

**Comment by Li-An** [comment]
Great. Do we have to wait for a long time ?

**Comment by mike-ward** [comment]
Fast enough for you :)
