### ISSUE TITLE
Remember cursor position in recent files plan

### ISSUE THREAD

**Issue by rogercloud** [mike-ward/Markdown-Edit#4]
My develop plan for the feature is listed bellow: 
1. Add cursor position with the file name in recent file setting on TextEditor unloading.
2. Set cursor position on TextEditor Loading.
3. If the cursor position is missing, reset it to 0 on file load.

How about it?

**Comment by mike-ward** [comment]
Sounds pretty much how I was planning on doing it. I was just going to append the offset as follows:

filename|offset

Because | (vertical bar) is a reserved character, it makes a convient separater. 

Note: I revised the roadmap with regard to symbols.

**Comment by mike-ward** [comment]
One other thing. You'll need to add an option to remember cursor position with a default of true. This is one of those behaviors that people love or hate.

**Comment by rogercloud** [comment]
I'll add an option in settings. We need to consider backwards compatibility when adding new features, such as adding new option in setting file.

BTW, maybe we can add an binary update feature in future release.

**Comment by mike-ward** [comment]
As long as you're adding options and not changing existing ones, there shouldn't be an issue with backwards compatibility. Missing options simply get the default value for that option. And yes, I know it changes behavior, but it's minor and can be turned off.

Binary update? (Send me a priivate message since that's outside the scope of this issue.)

**Comment by rogercloud** [comment]
In current design, there're two point where settings file is saved. One is creating fresh settings file, the other is changing theme in theme dialog. If users update to newer version and in that version we add some new option in settings file, they cannot add these options into settings file unless add them manually.

In consideration of above scenario, we may need one point to write settings back. Closing app event handler is good place. On the other hand, the app will write settings file every time it's closed even nothing is changed there. It's a trade off.

**Comment by mike-ward** [comment]
I understand your point. Honestly, it's not a concern for me. My preference (a strong one I suppose) is to not write files unless there is a change.

**Comment by rogercloud** [comment]
It's hard to detect change in option missing case, for that there's no change at all. So I would first try my way until there's a better way proposed.

**Comment by mike-ward** [comment]
As I stated earlier, this is not an issue for me. The missing option is simply missing. It does not merit writing the file every time on close. (So please, don't write the file on close).

**Comment by rogercloud** [comment]
OK, get your point. Won't do that. :-)

**Comment by mike-ward** [comment]
I found a way that addresses your concern. See App.xaml.cs.

**Comment by mike-ward** [comment]
I've implemented this feature. Had some time on my hands.

**Comment by rogercloud** [comment]
It's good to hear that, any feature left for version 1.2?

**Comment by mike-ward** [comment]
There's no save to HTML that saves the entire document including the
template. The current Ctrl+E option saves the only the generated HTML
fragment.

I was thinking something like `Ctrl+Shift+E` could export the entire HTML
document. Are you up for that? If so, open a new issue and have at it.
