### ISSUE TITLE
Symbols not displayed on Windows

### ISSUE THREAD

**Issue by zommuter** [mike-ward/Markdown-Edit#41]
![markdownedit-symbols](https://cloud.githubusercontent.com/assets/3686260/10070075/7db74400-62b0-11e5-9438-6336547b780c.png)

I guess those rectangles should be some unicode symbols which the font used doesn't support (on Windows 7).

**Comment by zommuter** [comment]
Duplicate of #14 though the lack of information on this anywhere outside Github *is* a bug IMHO...

**Comment by TongKuo** [comment]
Ref this: https://github.com/mike-ward/Markdown-Edit/issues/14

**Comment by mike-ward** [comment]
@zommuter Write a blog article about this and I'll link to it on the Markdown page.
