### ISSUE TITLE
Pasting an URL into a `[alt text](url)` link crashes

### ISSUE THREAD

**Issue by zommuter** [mike-ward/Markdown-Edit#42]
Pasting a simple URL such as `https://en.wikipedia.org/wiki/Lightweight_markup_language` into the parentheses of  `[lightweight markup language]()` causes a crash, while pasting it directly and adding the parentheses afterwards works but adds surrounding `<>`s.

**Comment by mike-ward** [comment]
Ummm. Not seeing that. Do you have a stack trace? (*.pdf files are already included)
 
The <> added to the link is intentional. This is legal Markdown syntax and guarantees the text is interpreted as a link. Very complicated links sometimes fool the parsers.

**Comment by zommuter** [comment]
My bad, the bug only occurs in a list, i.e. MWE:

    * [test]()

then paste a link into the parentheses.

**Comment by mike-ward** [comment]
Still not happening here at mind end. What url are you using?

**Comment by zommuter** [comment]
Hm, might be this only happens for `https` links such as `https://github.com/mike-ward/Markdown-Edit/issues/42#issuecomment-143742441`
