### ISSUE TITLE
small problem in Tiles (Stardock)

### ISSUE THREAD

**Issue by Li-An** [mike-ward/Markdown-Edit#43]
Hello,
I'm using Tiles from Stardock - http://www.stardock.com/products/tiles/ - and there is a little problem with Markdown Edit: Tiles usually shows one window for one program and with Markdown Edit, it shows five windows - see capture http://tof.canardpc.com/view/dfaa3e87-f0ea-4179-951f-59b0884a9e5d.jpg

And it's not big problem - Tiles is not perfect - but ME is the only program I use with this and it's a little boring. So if it's easy to correct :-)

**Comment by mike-ward** [comment]
Sounds like something you need to discuss with Stardock. If there's a simple fix they can recommend, I'll try to implement it.

**Comment by Li-An** [comment]
OK, I will ask them.
