### ISSUE TITLE
Please add a "Save as HTML" option

### ISSUE THREAD

**Issue by UweKeim** [mike-ward/Markdown-Edit#45]
#### Currently:

1. Export HTML to clipboard in Markdown Edit.
1. Fire up Notepad++.
1. Create new document in Notepad++.
1. Paste the HTML from the clipboard into Notepad++.
1. Click the "Save" button in Notepad++.

#### New:

1. Click the "Save as HTML" button in Markdown Edit.

**Comment by mike-ward** [comment]
Good idea. I'll add it to the todo list.

**Comment by mike-ward** [comment]
Implemented in 1.13
