### ISSUE TITLE
special copy of URL

### ISSUE THREAD

**Issue by Li-An** [mike-ward/Markdown-Edit#47]
Hello,
I like very much the automatic pasting of URL giving `<http://wwww.mydomain.com>`. But it's a little boring in the case where you write a  `[My domain](http://wwww.mydomain.com)` as < and > will be added automatically when pasting.
Maybe a At+Ctrl V or another shortcut could paste an URL without < and >

**Comment by mike-ward** [comment]
I appreciate that it's not as attractive but it's correct behavior and handles edge cases that would otherwise cause other issues.

**Comment by mike-ward** [comment]
I went back and looked at the issues that require the <> in urls. The fundamental issue is that browsers are for more forgiving when urls contain invalid characters vs. the Markdown compilers. Given that I should be able to detect most of these edge cases. So, I'll update a future version to remove the <> when it can.

**Comment by Li-An** [comment]
Nice :-)

**Comment by mike-ward** [comment]
Fixed in 1.12
