### ISSUE TITLE
When I insert a link — Markdown Edit crashes

### ISSUE THREAD

**Issue by online** [mike-ward/Markdown-Edit#48]
Hello!

I am using Windows 10 (x64). I took off screencast about this issue — http://take.ms/jP54v.
For inserting link, I used a combination of keys `Ctrl` + `V`.

**Comment by mike-ward** [comment]
While I don't doubt this is a bug in MDE I'm at a loss to reproduce it. If you can reproduce it in a debugging environment and send the info to me we'll have a better shot at fixing this.

**Comment by online** [comment]
@mike-ward Thank you for your quick reply. How do I start the editor in debugging environment?

**Comment by mike-ward** [comment]
You'll have to download the community issue of Visual Studio and then clone the repository. It's quite a bit of work if you've not done something like this before.

**Comment by online** [comment]
@mike-ward Sorry, but it's very difficult for me :neutral_face:

**Comment by online** [comment]
@mike-ward Thank you for the new version. Version 1.12 works for me correctly.
