### ISSUE TITLE
Saving snippets kills Markdown Edit

### ISSUE THREAD

**Issue by Li-An** [mike-ward/Markdown-Edit#49]
Hello,
thanks for the update. I have still the problem "saving snippets text file kills the program".

**Comment by mike-ward** [comment]
I'm going to need:

-  Your snippet file, before you make the change.
- . The exact steps including what you typed into the snippet file.

**Comment by Li-An** [comment]
OK
Content of the file:
```
now       $DATE("f")$ $END$
date      $DATE("d")$ $END$
time      $DATE("t")$ $END$

img       ![$alt_text$]($image_url$) $END$
link      [$link_text$]($link_url$) $END$

deb      ## $titre_h2$\n$intro_billet$**[$nom_plugin$]($CLIPBOARD$)** $contenu_billet$\n\n[notice type=notice]\n- site du plugin: <a href="$CLIPBOARD$">$CLIPBOARD$</a><br>
fin	 - compatibilité à ce jour: WP $version_WP$ > WP 4.3.1<br>\n- version testée: $version_testée$\n[/notice]
sea      **[search]$nom_propre$[/search]** $END$

tm        &trade;
cp        &copy;
reg       &reg;
```

I do not type anything. I open it in Notepad with F6, make Ctrl+S and Markdown Edit is killed.

**Comment by mike-ward** [comment]
I still can't repro this. Sorry.

**Comment by Li-An** [comment]
Strange. I have Win 7 64 bits.

**Comment by Tdue21** [comment]
For what it is worth, I can't reproduce it either.
