### ISSUE TITLE
Compiled 1.12 is detected as virus

### ISSUE THREAD

**Issue by seperman** [mike-ward/Markdown-Edit#52]
I just tried to install 1.12 and my Panda Antivirus did not let it happen.
Also here you can see the file on Total Virus:

<https://www.virustotal.com/en/file/431f890d0a9a0cec3279412690bf4d46c30a079dafc364b902fa693346cb2066/analysis/>

I have not tried to compile from the source yet. Not sure what might have caused this.

**Comment by mike-ward** [comment]
It's a false positive. The problem with pattern based scanners is well, they look for patterns.
