### ISSUE TITLE
Toolbar icons missing

### ISSUE THREAD

**Issue by jnm2** [mike-ward/Markdown-Edit#54]
Instead of toolbar icons, I'm getting the missing code point symbol:

![missing icons](https://cloud.githubusercontent.com/assets/8040367/10890465/083ad7f8-8166-11e5-86bb-4f82fe8b5056.PNG)

MarkdownEdit 1.13, Windows 7 SP1 x64, .NET Framework 4.6

[Re: your ego](http://mike-ward.net/2015/10/31/markdown-edit-1-13-released/) really nice software, BTW.

**Comment by mike-ward** [comment]
See issue #14
