### ISSUE TITLE
Implement Ctrl-P to print

### ISSUE THREAD

**Issue by sualeh** [mike-ward/Markdown-Edit#55]
Every now and then, I need to print the Markdown document. Please implement Ctrl-P to print the nicely formatted HTML output. Thanks.

**Comment by mike-ward** [comment]
You can right-click on the preview and select print now. Not sure what to do when Ctrl=P is pressed in the edit panel. Do I print the raw Markdown? It's a bit ambiquous what should happen. Have to think about it for a bit.

**Comment by sualeh** [comment]
Yes, that is what I do to print HTML. Let me know what action you would take when Ctrl-P is pressed in the edit panel. My vote of course is to print the formatted HTML output.

**Comment by mike-ward** [comment]
Fixed in 54fdfda

Will appear in next release.

**Comment by sualeh** [comment]
Thanks!
