### ISSUE TITLE
GitHub-style preview template

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#56]
Wanted the preview to look like if GitHub rendered it so I've prepared this small Gist:

https://gist.github.com/borekb/57bc575e38db2c99f1b5

(Just sharing it, this issue can be closed.)

**Comment by borekb** [comment]
BTW Markdown Edit is a lovely little editor, thank you for it!

**Comment by mike-ward** [comment]
Hi and Thanks. I like it better than current one. Will likely incorporate it into the next release.

**Comment by mike-ward** [comment]
available in next release.

**Comment by borekb** [comment]
For anyone interested, styles have been reverted in [1.30](https://github.com/mike-ward/Markdown-Edit/releases/tag/v1.30). Here's a GitHub repo with the up-to-date GitHub template (using native fonts as per [mid-2016 style update](https://twitter.com/mdo/status/752561058011754496).)

**Comment by mike-ward** [comment]
I've updated the [1.30](https://github.com/mike-ward/Markdown-Edit/releases/tag/v1.30) release notes to include this link. Thanks!

**Comment by borekb** [comment]
The link currently points to a tweet instead of the template but it's great that you added this info to the release notes, thanks.

**Comment by mike-ward** [comment]
Fixed...
