### ISSUE TITLE
Paste / import from OneNote

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#60]
Similar to "open DOCX", it would be nice if I would be able to copy OneNote text and paste it to MDE.

The challenge here is that while OneNote looks (and is) simpler than Word, its HTML is actually less style-based so for example bold text is not `<strong>bold text</strong>` but `<span style="font-weight: bold;">bold text</span>` (I think they must have gone insane when they implemented it like this).

There is [this project](https://github.com/cleannote/cleannote-csharp) that tries to convert some simple OneNote documents into Markdown but it doesn't have a good and usable UI. Maybe that functionality could be incorporated into MDE.

**Comment by mike-ward** [comment]
Interesting idea. I'll investigate and see what can be done.

**Comment by borekb** [comment]
Just noticed that when I export OneNote page to DOCX and then run it through Pandoc, it generates kind-of-OK Markdown. Does MDE use Pandoc to open DOCX files? If so, maybe I could bug them to improve the HTML / OneNote support :) On MDE's front, it would then be just about accepting the copied OneNote text from the clipboard and running it through Pandoc.

**Comment by mike-ward** [comment]
Indeed, MDE uses Pandoc to pen DOCX files.

**Comment by borekb** [comment]
Created an issue there: https://github.com/jgm/pandoc/issues/2522

**Comment by mike-ward** [comment]
Will revisit this when a converter is available.
