### ISSUE TITLE
Ctrl+Plus, Ctrl+Minus, Ctrl+0 don't work on numpad

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#61]
These keyboard shortcuts don't work on the numpad of my keyboard (they do on the main keyboard).

**Comment by borekb** [comment]
BTW it would be nice if increasing font size also similarly scaled the preview.

**Comment by borekb** [comment]
@mike-ward I forgot, is the scaling sync tracked in some separate issue or not? It's still something I would like to see in MDE.

**Comment by mike-ward** [comment]
The last thing I want to get into is zooming both views. Hell, I get enough grief as it is with the whole 125% thing.
