### ISSUE TITLE
Paste URL as is

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#64]
Right now, `Ctrl+V` adds `<` and `>` around the URL so it looks like

    <http://example.com>

I think MDE is trying to be too clever here, for instance if I am inside the `[]()` markup I just want to paste the plain URL. I know I can do `Ctrl+Shift+V` but it feels to me that the default paste should do just that.

**Comment by mike-ward** [comment]
I like that it understands what URL's are. I appreciate you feel otherwise but I like it this way. The only time I've found I don't want this is when I'm pasting into code blocks. I've got it my todo's to figure out how to detect that.

**Comment by borekb** [comment]
Would it be possible to make this configurable?

**Comment by mike-ward** [comment]
For the `Ctrl+L` case I can leave them out. 

In CommonMark, bare URL's are not recognized as links. GitHub flavored Markdown does understand bare urls. Surrounding the URL with angle brackets is legal in both Markdown variants.

I really don't see a use case (other than pasting into code blocks) where brackets cause an issue. Does \[title\](link) vs. \[title\](\<link\>) really matter?

**Comment by borekb** [comment]
Interesting point, I didn't know that < .. > is required in plain Markdown to highlight a link (too used to GFM and other "Markdown extra" dialects I guess). Then I agree, it might actually be a good thing to surround it in angle brackets but maybe it should be on the "paste special" action (`Ctrl+Shift+V`)? I somehow feel that paste should just paste in a plain-text editor...

**Comment by borekb** [comment]
BTW on my PC, the paste that is adding the angle brackets takes about 2 seconds to complete. Paste without them is instant. Might be some performance issue somewhere.

**Comment by mike-ward** [comment]
MDE issues a HEAD request to figure out if the link is an image. If so, it pastes the link as an image link. It's kind of neat the first time you use it.

I'll add an option to disable this. I can see where it might get in the way in some instances.

**Comment by borekb** [comment]
Oh that is a nice little feature indeed.

What do you think about just swapping paste and paste special in this case? I think I would use the current behavior sometimes now that you've described it to me, I'd probably just prefer the default paste to be a "stupid paste".

**Comment by mike-ward** [comment]
Probably not. I also intend to add something called *link pasting* where selected text will get incorporated into a link tag when pasting URL's. It's a Markdown editor first and most of time when a link is pasted, the intention is that is should be a link.

By the way, when `Alt+F` reformats a document, it removes the angle brackets where appropriate.

**Comment by borekb** [comment]
OK looking forward to the change. BTW you said you're doing a HEAD request to find out whether the URL is an image. While it is probably the only way to be 100% sure whether the resource is an image or not, maybe just checking the file extension would work 98% of the time and would save that delay on every paste. Might be a reasonable trade-off..

**Comment by mike-ward** [comment]
I'll add that optimization. It's surprising the number of urls I use that don't have those extensions (Imgur for instance).
