### ISSUE TITLE
Email address missing from preview

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#65]
I write this:

![mde-email-md](https://cloud.githubusercontent.com/assets/101152/11149505/6c3038be-8a23-11e5-97fa-7f9dbb81b873.png)

and the preview shows this:

![mde-email-preview](https://cloud.githubusercontent.com/assets/101152/11149521/8fbdf4ba-8a23-11e5-96c8-c84697125fd6.png)

**Comment by mike-ward** [comment]
CommonMark requires surrounding angle brackets to recognize bare urls. GitHub and other extensions do not.

**Comment by borekb** [comment]
Here the email address is completely missing, not just unrecognized. The preview should look like this: [link](http://spec.commonmark.org/dingus/?text=%20-%20**Gmail**%20%2F%20info%40versionpress.net%20is%20our%20public%20...%0A).

**Comment by mike-ward** [comment]
Occurs with the GitHub markdown render but not the CommonMark render. Looks like a bug in Pandoc. Care to log bug there?

**Comment by borekb** [comment]
Cannot reproduce it with Pandoc, see [this example](http://pandoc.org/try/?text=+-+**Gmail**+%2F+info%40versionpress.net+is+our+public+...&from=markdown_github&to=html).

**Comment by mike-ward** [comment]
Using the following command line switches

    pandoc -f markdown_github -t html5

Produces the following HTML:

    <ul>
    <li><strong>Gmail</strong> / <script type="text/javascript">
    
    </script>    <noscript>&#x69;&#110;&#102;&#x6f;&#32;&#x61;&#116;&#32;&#118;&#x65;&#114;&#x73;&#x69;&#x6f;&#110;&#112;&#114;&#x65;&#x73;&#x73;&#32;&#100;&#x6f;&#116;&#32;&#110;&#x65;&#116;</noscript> is our public ...</li>
    </ul>

MDE does not render scripts for security reasons. Why Pandoc renders this as script instead of plain HTML I don't know, but it's a bug in Pandoc as far as I'm concerned.

**Comment by borekb** [comment]
Ah, I only tried HTML. Will report a bug.

**Comment by borekb** [comment]
Filed pandoc/issues/#2528.

**Comment by borekb** [comment]
Aha, the issue is that Pandoc obfuscates mailto addresses by default to that ugly script, and it does so consistently. It's a question whether Pandoc should do it or not but a quick fix in MDE would be to add `--email-obfuscation=none` parameter.

**Comment by mike-ward** [comment]
Easy enough to add.
