### ISSUE TITLE
Emoji preview if GitHub rendering is selected

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#66]
`:boom:` -> :boom: :)

**Comment by mike-ward** [comment]
I don't think Pandoc supports this.

**Comment by mike-ward** [comment]
By the way, I limit users to 20 feature requests per day :)

**Comment by borekb** [comment]
Yep, sorry, these suggestions are out of pure love for your editor :)

**Comment by mike-ward** [comment]
Just having some fun with you :)

**Comment by mike-ward** [comment]
Confirmed, Pandoc does not support this. I'll leave it as an open issue in case someone gets inspiration to add it.

**Comment by borekb** [comment]
Filed an issue there, `#2523`.

**Comment by borekb** [comment]
BTW, is there a way to write Pandoc extensions easily, without knowing Haskell? Or MDE extensions in general? For instance, our docs system is 99% Markdown and 1% custom rules (for example, `[TODO ...]` is a `<span class="highlight">...</span>`). It would be really great if I could add custom parsing rules that accept Markdown and spit out HTML used in the preview pane.

**Comment by mike-ward** [comment]
Document generation is outside the scope of Markdown Edit's original aim. There are plenty of document generators for that purpose. My goal was to make authoring Markdown documents easier.

**Comment by borekb** [comment]
This was about custom extensions for preview, not document generation. There are many dialects of "Markdown" and if I could customize the preview using some kind of standard mechanism (regexes in the worst case), it would help me see the document the same way I will eventually see it rendered on the web.

**Comment by mike-ward** [comment]
I could see this happening a couple of ways. From my perspective, the best solution would be to embed the transformation rules into the document itself using some escape mechanism (YAML markup perhaps). The CommonMark standard has stated that they intend to add a standard mechanism for extensions. We can revisit this when that mechanism is in place.

**Comment by borekb** [comment]
Emoji support has just been added to Pandoc: https://github.com/jgm/pandoc/issues/2523

I'm going to look into the source code if I could add "my own Markdown" easily. I often want that and I think any renderer could be added quite easily (just let me specify a CMD / EXE and use what was returned in the preview pane).

**Comment by mike-ward** [comment]
A converter simply has to simply implement the `IMarkdownConverter` interface (it has one method). The bigger question is how to expose the functionality. The interface or/and configuraton has to allow selection of a converter. Please open a separate issue so we can discuss further.

**Comment by mike-ward** [comment]
Available in next release.

**Comment by borekb** [comment]
Done that.
