### ISSUE TITLE
Pluggable Markdown conversion

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#67]
Continuing the discussion from #66, an extensible system for previewing rendered HTML would be nice. For example, I might want to use Markdown Extra or some other slightly different dialect.

At the very basic level, I would be happy enough with a config option like `MarkdownProcessor` where I would just provide a command line that converts Markdown to HTML. For example:

    "MarkdownProcessor": "pandoc -f markdown_phpextra -t html5"

and that's it. If writing C# code and compiling DLLs could be avoided, I would very much like that :)

For my point of view, there doesn't need to be a UI for this, at least at first.

**Comment by mike-ward** [comment]
That seems reasonable. The only impact on the UI would be to disable the selection of CommonMark/GitHub selection when this config is set.

**Comment by borekb** [comment]
:+1:

**Comment by borekb** [comment]
Does this still work in 1.25? Adding `MarkdownProcessor` setting does not seem to do anything and the UI for switching MD impl is not disabled.

**Comment by mike-ward** [comment]
No, it no longer works. I just forgot to cleanup the interface.

**Comment by mike-ward** [comment]
Probably broken. I don't use it so it doesn't get tested much.

**Comment by borekb** [comment]
Came back to this because GitHub has mutliple rendering modes, e.g., wikis are rendered differently than issues. Wanted to implement a script to call the real GitHub API but couldn't hook it to MDE.

**Comment by mike-ward** [comment]
I'll have a look. I only tried it with launching Pandoc. Might have to do something different for a script. Send me the script if you don't mind.

**Comment by borekb** [comment]
It's basically something like:

```php
<?php
$client = new GuzzleHttp\Client();
$res = $client->request('POST', 'https://api.github.com/markdown', [
    "json" => [
        "text" => "hello *world*",
        "mode" => "markdown"
    ],
    "verify" => false
]);
echo $res->getBody();
```

and then calling

```
php convert.php
```

from the console.

**Comment by borekb** [comment]
Here's the full repo: https://github.com/borekb/github-md-preview
