### ISSUE TITLE
Review mode

### ISSUE THREAD

**Issue by rogercloud** [mike-ward/Markdown-Edit#7]
Develop Plan:
1. Search current directory where the editing document locates for other markdown file.
2. Provide key binding like Ctrl+Shift+P and Ctrl+Shift+N for navigation.

The other  way is let user set Markdownd Edit to review mode by Ctrl+Shift+R, And only N and P is required in navigating among docs.

Which way do you prefer?

**Comment by mike-ward** [comment]
I haven't given a lot of thought to review mode. Previous/Next file options are obvious and simple to implement. This may be enough but I'm feeling I want something more along the lines of what Brackets.io does with it's file navigation pane. Then again I'm loath to introduce another window or pane. We're going to need a bit of brain storming here. 

One idea would be to add an "Show files in folder" dialog with some quick nav options like search, next/prev file etc. Again, I haven't thought this one through much.

**Comment by rogercloud** [comment]
"show files in folder" is a good idea, which is also taken by some excellent editor, such as sublime text. 

When I consider it, I wondered about what kind of users are you targeting when you design the app. It's the key point. As shortcut key binding is one of the main feature of this editor, and settings file is also included, I guess people like programmers may be one of the target audience.

According to above consideration, sublime text's way navigation is also a good example. It pops up a search box (auto-complete and fuzzy match) to search the files in the directory.

Besides that, the review mode feature also reminds me of some ideas that turn the editor into some more powerful tool like evernote, which only focuses on markdown text. If you're interested in it, I can open another issue to talk about that. I totally understand if you say no, because making a pure editor is also a great job and meets the philosophy of Unix.

**Comment by mike-ward** [comment]
I'll have to look at Sublime sometime. I like the way Brackets.io handles the file stuff but that introduces a new panel. Not sure if I want to go there yet.

**Comment by rogercloud** [comment]
Sublime's directory view is similar to Brackets.io, I also don't want to bring a new panel. So my suggestion is providing a light-weight search box for directory navigation and wait for user's feedback.

**Comment by mike-ward** [comment]
Here's an idea. Look at the V1.3 branch (you'll need VS 2015 CTP 5). The settings dialog uses a flyout window from the UI toolkie (MahApps). I could see a directory navigation using a flyout window.

**Comment by mike-ward** [comment]
Also, if you're looking for a project, the Find/Replace implementation is pretty lame. It could use some TLC.

**Comment by mike-ward** [comment]
After using MDE for almost a year I've found that review mode is something I've even thought about.
