### ISSUE TITLE
Preview is blurry on high-density displays

### ISSUE THREAD

**Issue by barryvan** [mike-ward/Markdown-Edit#71]
On a high-density display (like a Surface Pro 3), everything except the preview is clean and sharp. The preview itself, however, appears to be scaled up from a smaller rendering.

**Comment by mike-ward** [comment]
Which operating system? Also, can you supply a screen shot? (GitHub issues supports drag and drop upload of images).

**Comment by h2dvnnet** [comment]
here ![ElqwgHV.png](https://i.imgur.com/ElqwgHV.png)

**Comment by mike-ward** [comment]
Looks like any other web page to me. Am I missing something?

**Comment by h2dvnnet** [comment]
Just zoom, u will see the different, it's blurred.

**Comment by mike-ward** [comment]
I did zoom it earlier. Not seeing it. What version of Windows? (Why do I always have to ask).

**Comment by h2dvnnet** [comment]
Windows 10 64bit with high DPI screen. And i think this image can help you see the dif
![untitled](https://cloud.githubusercontent.com/assets/12293622/11375270/e97449e0-930c-11e5-9c72-7b781f247374.png)

**Comment by mike-ward** [comment]
Looks like the default Internet Explorer Zoom is not 100%. Try adjusting the zoom with `Ctrl+MouseWheel`. MDE makes no adjustments to zoom levels.

Another thing to try is adding `body { zoom: 100%; }` to the style sheet. (or 90% to make it smaller)

Are you running your system display at 125%? If so, try 100%.

I have two high windows 10 systems I test this on and they look same on my systems. Might be a driver issue or some other system setting. It's hard to say.

**Comment by h2dvnnet** [comment]
I tried to zoom, change screen scale, but it doesn't working, i also tried to disable display scaling on high DPI settings and it still blurred.
![untitled](https://cloud.githubusercontent.com/assets/12293622/11389107/4523b6ec-936f-11e5-8360-0f97406ade86.png)

**Comment by mike-ward** [comment]
So maybe it has nothing to do with high DPI?

Is the screen on the left an exported version from MDE of just the GitHub view?

**Comment by h2dvnnet** [comment]
yes it is. and can we change the default MDE's render into chrome or firefox?, i think it can solve the problem.

**Comment by mike-ward** [comment]
Yes it is what? And is it rendered in IE or Chrome or Firefox? This twenty questions thing is getting old...

I wouldn't hold my breath about hosting Chrome or Firefox. I've not seen it done sucessfully. There's Awesomium, which I tried. It's performance was terrible.

**Comment by jschwanz** [comment]
I'm having the same trouble. My system display is set to 125% on Win7.

I'm not a C# programmer, but I do see a lot of references to AutoScaleMode on StackOverflow et al with regards to "non-standard" DPI settings and WinForms apps.

**Comment by mike-ward** [comment]
You can disable DPI scaling on a per-app basis. 

![image](https://cloud.githubusercontent.com/assets/567927/11512512/778bb482-983c-11e5-9d43-3140aaa03ffd.png)

**Comment by mike-ward** [comment]
Another thing to try is to add 
```html
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, minimum-scale=1.0">
```
To your template header

**Comment by jschwanz** [comment]
I tried both of those suggestions, and neither worked.

**Comment by mike-ward** [comment]
Bummer. Not sure there's anything else I can offer. I have two systems with high API and %125 scaling and it looks fine. Maybe it's a driver issue.

**Comment by mike-ward** [comment]
Also, Ctrl+Mousewheel changes the zoom in preview. Does that help?

**Comment by bdelaney** [comment]
Hi Mike,
Thanks for this Markdown package. Just trying it out today. Have been using VS but wanted something much slimmer. You have made it very minimalistic. Kudos.

Jumped into this issue because I have a high DPI (not 4k) monitor and at 100/125/150% the preview pane is clear for me.

**Comment by borekb** [comment]
Just switched my laptop from 100% to 125% and can confirm that the preview pane is "broken" - the preview pane is not only blurry but it also seems that the pane in general is wider than what fits to the screen, leading to some words missing:

![mde-preview](https://cloud.githubusercontent.com/assets/101152/12221625/57654f48-b7a3-11e5-8e77-ba3167840060.png)

**Comment by mike-ward** [comment]
This appears to be driver issue that I have no control over. I simply don't see this behavior wihen switching to 125%. And others have reported they can't reprodiuce the issue. The fact of the matter is the preview is Internet Explorer and it will do what Internet Explorer does. So please, lets just give this a rest. Run at 100% or move on but I'm done with this issue.

**Comment by borekb** [comment]
Is there an easy replacement for using IE for preview? It is behaving strange even on 100%, for example, clicking the preview pane doesn't give the application focus etc. I'm not familiar with WPF but maybe this preview component is simply problematic.

**Comment by borekb** [comment]
One more observation: when I change the DPI settings in Windows 10, most apps re-layout themselves, change icon sizes etc. MDE is unaffected by the change - not a single pixel changes in it.

Unfortunately, I don't know WPF much (well, hardly at all) but found this: [link](https://msdn.microsoft.com/en-us/library/windows/desktop/ee308410%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396). If that's all implemented or irrelevant please ignore me.

**Comment by mike-ward** [comment]
Weird. I run one monitor at 125% and the other at 100% and the only application I see that adjusts it's layout is the windows file explorer. MDE appears fine on both screens.

WPF applications are vector drawn making them DPI aware. Per monitor DPI is a special case which I don't see as applicable to MDE (thanks for the link however, I wasn't aware of the per monitor feature).

I don't mean to sound dismissive about this but it really is not anything I can control. To date, MDE has about 250,000 downloads. So far, only a few have reported this issue so it is likely not a wide spread issue. Then again, maybe as more people upgrade to Windows 10 I'll hear about it more.

As to the clicking and not getting focus in the browser window. That's an issue with hosting any browser in a windows control due to ActiveX issues. The lastest version fixes this issue by adding a message pump hook and reactivating the application when necessary.

I checked into hosting Chrome. There are similar complaints on the forums about blurriness when hosted in an ActiveX container.

Is there an issue here? Likely, but I suspect it has to do with some combination of displays and drivers that is outside MDE's control.

Do keep pressing the issue if you find out additional information. It's not that I don't believe you, but without a reproducable secenrio here, there's little chance I can detect if there's something MDE can do to correct the problem.

**Comment by borekb** [comment]
250k downloads? Wow that's HUGE!

I'll just add comments to this issue whenever I find something new (or strange). Just want to stress that this happens to me when I have MDE open and change the DPI in Windows during the logon session. When I don't change the DPI, all is fine even if I have one monitor on 100% and the other one on 125% like you do. It's the *change* that's causing the trouble.

**Comment by mike-ward** [comment]
250K is about normal for one of my apps a year out. Sounds big but by Internet standards it's small. I've had several other programs over the years go 1M+.

>  It's the change that's causing the trouble

I missed that detail. Thanks for clarifying.

**Comment by borekb** [comment]
On my home PC where the setup is very standard - one FullHD monitor, Windows set to 100% DPI and I've never changed that value - the preview suddenly become blurry after some update (not sure which exactly but I guess it was around 0.19). This is quite strange because MDE on this PC has always been alright.

**Comment by mike-ward** [comment]
Does it revert back when older versions are installed?

**Comment by mike-ward** [comment]
AMD drivers are known to have this problem. http://www.digitalcitizen.life/fix-fuzzy-fontsblurry-text-problem-windows-live-applications-internet-browsers

**Comment by borekb** [comment]
Will try an older version when I'm back at home. Also, thanks for the link, it's true that I have AMD drivers, will check it out.

**Comment by borekb** [comment]
1.18 is the last release with crisp fonts. Everything newer is blurry for me.

BTW "Morphological filtering" in AMD driver settings is off.

**Comment by mike-ward** [comment]
OK, let's try a few things.

http://www.expirebox.com/download/51dd4b3142ef52e168375b2ba9234aca.html

This version turns on something called layout rounding.

**Comment by borekb** [comment]
Crisp!

**Comment by mike-ward** [comment]
Well, there it is then. I see the issue now. My eyes are simply not good enough to see the difference. Only when I zoom in about 200% is the difference obvious.

Here's the differnece with Layout Rounding on right:

![image](https://cloud.githubusercontent.com/assets/567927/12568740/2f81c958-c396-11e5-87c5-393d6f4541b3.png)

Anyways, I'll push an update out tonight with this setting. Hopefully, I can put this puppy to bed finally.

**Comment by borekb** [comment]
Great find, you'll certainly be happy to see this issue closed for good :) I'll try tomorrow on my other PC with different DPIs as mentioned above (if this is the same issue, I'm not sure).
