### ISSUE TITLE
Copied text in OneNote is pasted as an image in MDE

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#73]
Steps to reproduce:

1. Open OneNote
2. Write something
3. Copy it
4. Ctrl+V in MDE
5. Image (??) of the text is uploaded to imgur and pasted

This is what the clipboard looks like after copying in OneNote:

![image](https://cloud.githubusercontent.com/assets/101152/11320541/1073fab8-909c-11e5-987b-2497e222626d.png)

Maybe the "OneNote 2010 Internal" format is causing trouble?

**Comment by mike-ward** [comment]
Oddly, I'm not sure this a bug. MDE accepts images from the clipboard and uploads them to Imgur. Since OneNote is adding an image to the clipboard it makes sense that MDE should use it.

**Comment by borekb** [comment]
Is there an order to those clipboard formats as per the screenshots above? Should the app accepting the paste go from top to bottom and see if it supports the given format? For example, OneNote will handle the top-most "OneNote 2010 Internal" format, MDE might accept System.String while something like MS Paint might use the bitmap? This would make sense to me but I'm not sure how various clipboard formats are intended to work.

**Comment by mike-ward** [comment]
This is one of those no win situations IMO. One could argue that images should be preferred. Images tend to contain richer content. 

There is an HTML format in there and I tried importing it. Of course OneNote had to throw extra "crap" into their HTML format. To make matters worse, OneNote uses tables for layouts, which won't translate to CommonMark.

OneNote is clearly designed to play well with Office apps, but not others.

Support for pasting from OneNote is therefore limited to image imports. I know that's not the answer you were looking for, but I see this as an issue with OneNote and not MDE.

**Comment by borekb** [comment]
Can you just take the plain text string representation? That's what other text editors do and sounds very natural. (I agree that OneNote's HTML is crap, I don't know why they had to spoil it like this when Word has an OK HTML export nowadays.)

**Comment by mike-ward** [comment]
Since MDE can understand images I don't see why it shouldn't use the image format. Other text editors don't understand images and are limited to text. 

What if the only thing you're pasting from OneNote is an image? I assume the text string is empty. Do I paste the image? Now I'm into a bunch of special case logic for OneNote:

if OneNote and text string empty and image bla bla bla...

It's a rathole I'm not willing to go down.

**Comment by borekb** [comment]
Maybe I have a simplistic view of this but isn't the algo just:

 - If the clipboard contains text, paste it
 - Else, if the clipboard contains a bitmap, paste it
 - Else, do nothing

**Comment by mike-ward** [comment]
Unitl some image paint program comes along and adds some helpful text in it's clipboard format. What works for OneNote might not work in other cases. Again, the only reason other "text editors" work is because they don't understand the image format.

I could always ignore the clipboard image format. That at least removes any abuguity about pasting.

**Comment by borekb** [comment]
I think image pasting is a cool feature, just that text should be preferred over bitmap if clipboard contains both. That will happen only in very rare cases anyway (tried a couple of image editors and none added a plain text to clipboard though it's certainly a possibility from a technical point of view).

Maybe I feel so strongly about this because I copied some private text into clipboard, pasted it into MDE and it uploaded it to a public service from where I couldn't even delete it :) Never happened to me before even though I copy/paste frequently between OneNote and other apps.

**Comment by mike-ward** [comment]
I can see the privacy issue coming up in other situations. I'll remove auto image pasting.

**Comment by borekb** [comment]
As I said, I think it was a really cool and useful feature, but you're right it needs to be handled carefully. For example, if it only worked when I have provided an imgur authentication and am uploading to something I can control, then it would perhaps be nice to re-introduce it. But as things stand, it's probably a good idea to remove it as you did. Thank you.

**Comment by mike-ward** [comment]
Yeah, it's a bit sad since I personally use that feature a lot. Part of the push and pull of applicaiton development. Thanks for all your suggestions.
