### ISSUE TITLE
Find doesn't work with a TAB character

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#77]
When I try searching for `	• ` (that's TAB followed by an unicode character for bullet followed by a space) I get no results even though this very text was copy/pasted into the Find dialog of MDE. The TAB character is causing the issues - the workaround is to switch to regex search and use `\t• ` but maybe it's still a small bug in MDE?

**Comment by mike-ward** [comment]
I would have to enable the textbox to accept tabs (the default is false). This would break tab-key navigation in the dialog. Since there is a work around I think it's better to keep the current behavior.

**Comment by borekb** [comment]
Agreed
