### ISSUE TITLE
Some suggests

### ISSUE THREAD

**Issue by 3895177** [mike-ward/Markdown-Edit#79]
1,add format shortcuts
2,add files manager,show the files list,easy to manage files.
3,use the local images,save the images to the document's directory.If the document do not save,save them when ducument saveing.

**Comment by 3895177** [comment]
correct:3,use the local images,save the images to the document's directory.If the document do not save,copy them when ducument saveing.

**Comment by mike-ward** [comment]
1.   Format shortcuts already exist (if I understand the request correctly)
2.   A file manager makes no sense without some form of multifile editing capability.  
      That means either using tabs or some side panel (like Atom or VS Code).  
      It's a big undertaking and adds a lot of noise to the interface.  
      I'm electing not to do this.
3.   Saving images to the local folder makes no sense to me.  
      A use case might clarify things.

**Comment by borekb** [comment]
Agree with 2. MDI will probably be oft-requested but I agree that the simplicity of SDI is a strong point of Markdown Edit.
