### ISSUE TITLE
Feature propose

### ISSUE THREAD

**Issue by rogercloud** [mike-ward/Markdown-Edit#8]
I have some feature in mind:
1. Add line number and also provide setting option to turn it off.
2. Let user search amount headers, the way like go to line. Currently only support next\previous header, it's hard to use in large document.

**Comment by mike-ward** [comment]
1. Line numbering is already there (it's easy to miss in the settings)
2. I've seen something like this in WriteMonkey with its, "Table of Contents" like control for doucment navigation. Interesting idea. I'm not sure if it warrents implementation at this time. It's easy to overload a program like this with, "Wow, that's cool, sfuff" that may only be useful to a small minority. Don't get me wrong, it's a good idea, just maybe not now. I would like to see the program get some more traction and solicate feedback from users on this.

Something to think about: Take a look at mermaidjs. I'm intriqued by the idea of adding other, "Markup Like" stuff like this. Mermaid has the advantage of being entirely in JavaScript so it can be added in-line to the template and exported as a stand alone html file.

Open a new issue if you want to discuss mermaid futher.
