### ISSUE TITLE
Local mathjax

### ISSUE THREAD

**Issue by shumtravi** [mike-ward/Markdown-Edit#80]
It possible to put mathjax and mathjax-scripts.js locally in distribution of Markdown-Edit to keep formulas rendered without internet connection?

**Comment by mike-ward** [comment]
I'm not entirely sure it's just one script. MathJax can download other resources as it needs them. You can modify the HTML template to point to a local one and see how that works.

**Comment by mike-ward** [comment]
Just looked at the MathJax distribution. It's 38MB zipped. That's more the entire MDE distribution. I'm going to have to pass on this one.

**Comment by mike-ward** [comment]
I did some more research and discovered Katex. Probably not as robust as MathJax but can be embedded locally. Any thoughts about this? Does Katex work well enough?

**Comment by shumtravi** [comment]
Looks like KaTex is lighter and faster, but with some missing features. [Comparison.](http://www.intmath.com/cg5/katex-mathjax-comparison.php)

**Comment by mike-ward** [comment]
Bummer. Looks like Katex has some IE issues as well. 

I downloaded and extracted the MathJax scripts. 
It took 6 minutes to unzip the files. (32,000 files and 1,900 folders)

That would make for one long install.
