### ISSUE TITLE
Backspace inconsistent when using block highlighting

### ISSUE THREAD

**Issue by cyotek** [mike-ward/Markdown-Edit#82]
Hello,

I was impressed when I found Markdown-Edit supports block selection, however I did find a slight issue with the backspace key. I currently use MarkdownPad Pro 2, but was thinking of switching to Markdown-Edit as it starts incredibly fast, and actually works properly in Windows 10 (although I suspect that for me the lack of MDI support in Markdown-Edit will be a deal breaker in the end).

It's a little awkward to describe, hopefully these steps will make sense.

* Select one or more character columns using block select
* Press backspace - the selected characters are deleted
* Press any other character key - the character will be inserted on each line from the original selection
* Press backspace again - this time, only the character from the line where the original block select ended will be deleted
* Press any other character key - this time, the character will only be inserted on the line where the original block select ended, the "multi line cursor" (for want of a better description!) has been lost

It is easy enough to repro by following the steps if the step descriptions themselves don't really help. Performing the same series of actions in MarkdownPad/Visual Studio/SSMS works "as expected", although I noted that Word behaves the same way as Markdown-Edit (perhaps because it is most often used with variable width fonts?). I prefer how VS does it though :)

Thanks;

**Comment by mike-ward** [comment]
Block selection is a feature of Avalon Edit, the editor control that Makrdown Edit uses. It might be better to report it there. I don't do anything special to enable or support it.

**Comment by cyotek** [comment]
Thanks. I just checked their repo and it looks like it was logged as [issue 22](https://github.com/icsharpcode/AvalonEdit/issues/22) in Dec 2014 - I shan't hold my breath for a fix then!

I'll close this as not much you can do about it.

**Comment by mike-ward** [comment]
It bugs me that Microsoft doesn't have decent editor control for WPF (or Forms for that matter). Relying on a third party for a fundemental control is not good.
