### ISSUE TITLE
Paste image from clipboard to local file

### ISSUE THREAD

**Issue by toSvenson** [mike-ward/Markdown-Edit#85]
Use case: Writing of documentation where a lot of screenshots are used.

Automatically saving to a .png in /images-folder (relative to .md-file) and inserting as image in markdown.

Ideally using a user configurable mask: e.g.   /images/{image-file}?raw=true
(The sample will make the image work on GitHub commits out-of-the-box)

**Comment by borekb** [comment]
Easy pasting of images from the clipboard would be great.

**Comment by lennybacon** [comment]
+1. Would be great

**Comment by moser96** [comment]
+1 yes I'm waiting for it.

**Comment by mike-ward** [comment]
Implemented v1.23
