### ISSUE TITLE
Support for CriticMarkup

### ISSUE THREAD

**Issue by mikjsmith** [mike-ward/Markdown-Edit#87]
Vote for support for CriticMarkup (http://criticmarkup.com/) - this would enable collaborative working, critical for any writing project. Uses five marks.

**Comment by mike-ward** [comment]
The only processor for this is written in python. If a javascript version (that can run in a browser) becomes available, please reopen it.

**Comment by mikjsmith** [comment]
The other option for collaborative writing  is to have something that begins to approach "track changes". An initial though for this would be to enable a differencing algorithm between different versions of a document. Would this work OK?

How about something like jsdiff (http://kpdecker.github.com/jsdiff/) or xindiff??
