### ISSUE TITLE
Flowchart and Sequence Diagrams like Stackedit.io

### ISSUE THREAD

**Issue by lennybacon** [mike-ward/Markdown-Edit#88]
Stackedit (https://stackedit.io/editor) has the really nice ability to render diagrams.

Sequences
http://bramp.github.io/js-sequence-diagrams/

Flowcharts
http://adrai.github.io/flowchart.js/

If the editor would support this it would be mind blowing!

**Comment by mike-ward** [comment]
This can done right now by adding the scripts yourself. The technique would be similar to how math equations are done.

See http://markdownedit.com/markdown-edit-math-equations/

If you put a template together, I'll add it as an alternative template download.

**Comment by lennybacon** [comment]
I just added this below the MathJax script in the template to make it work.

```
<script src="http://bramp.github.io/js-sequence-diagrams/js/underscore-min.js"></script>
<script src="http://bramp.github.io/js-sequence-diagrams/js/raphael-min.js"></script>
<script src="http://bramp.github.io/js-sequence-diagrams/js/sequence-diagram-min.js"></script>
<script src="http://adrai.github.io/flowchart.js/flowchart-latest.js"></script>
<script>
function drawDiagrams() {
  //alert(document.body.innerHTML);
  var sequences = document.getElementsByClassName('language-sequence');
  //alert(sequences.length);
  for (var i = 0; i < sequences.length; i++) {
    var innerHtml = sequences[i].innerHTML;
    //alert(innerHtml);
    var statement = innerHtml.replace(/\&gt\;/mg, ">")
    //alert(statement);
    var diagram = Diagram.parse(statement);
    sequences[i].innerHTML = '';
    diagram.drawSVG(
      sequences[i],
      {
        theme: 'hand'//'simple'
      }
    );
  }

  var flows = document.getElementsByClassName('language-flow');
  //alert(flows.length);
  for (var i = 0; i < flows.length; i++) {
    var innerHtml = flows[i].innerHTML;
    //alert(innerHtml);
    var statement = innerHtml.replace(/\&gt\;/mg, ">")
    //alert(statement);
    var diagram = flowchart.parse(statement);
    flows[i].innerHTML = '';
    diagram.drawSVG(
      flows[i]
    );
 }
}

if(window.attachEvent){
  window.attachEvent("load",  drawDiagrams);
}
if(window.addEventListener){
  window.addEventListener("previewUpdated",  drawDiagrams);
  window.addEventListener("load",  drawDiagrams);
}
</script>
```

Btw.: http://markdownedit.com/markdown-edit-math-equations/ returns a 404

**Comment by mike-ward** [comment]
Fixed link (trailing backslash)

**Comment by mike-ward** [comment]
Interesting you needed the add a `load` listener. The `previewUpdated` should have fired after the load. Also, I found that loading the scripts async can resolves issues at load.

Nice work.

**Comment by RoyiAvital** [comment]
How can I configure MDE to use `$ $` for inline math?

Moreover, I enabled GitHub MarkDown Flavored yet `[]` and `[x]` doesn't work.

Thank You.

**Comment by mike-ward** [comment]
Support issues should be directed to the [Markdown Edit forum](https://muut.com/markdown-edit)

**Comment by RoyiAvital** [comment]
I already found a way and added it into the Wiki :smile: .

Thank You.
