### ISSUE TITLE
mermaid in Markdown Edit

### ISSUE THREAD

**Issue by rogercloud** [mike-ward/Markdown-Edit#9]
It's amazing!!! A way to bring graph to the edit.

We can let people edit the graph in the place where they want to insert the pic, and introduce some syntax that doesn't conflict with markdown's to indicate the start and end of mermaid text. For example:

%MERMAID%
....mermaid text....
%END MERMAID%

When displaying the html on the right or export to pasteboard, we first filter this out and insert some hint at the place. After CommonMark parses the text into html, we insert it back with `<div class="mermaid"></div>` arounded.

**Comment by mike-ward** [comment]
I think mermaid is a neat idea as well.

The CommonMark Engine has to be told not to touch mermaid content. As it happens, this is already built into the CommonMark specification. Inline HTML is escaped, so to speak, from parsing so the `<div class='mermaid"></div>` tag actually produces the correct behavior.

Of course, a snippet could be added to make adding the tag easier.

Another thing to consider is that mermaid produces SVG which is targeted to work in a browser. The tag is a signal that this wiill only work in a browser.

So really, the work to implement this feature is to browserfy the mermaid stuff and add it inline to the default template. It's almost a freebie code-wise.

**Comment by mike-ward** [comment]
Just tried this. Mermaid is not supporting IE at the moment. I put in an issue. It looks like a minor problem.

**Comment by rogercloud** [comment]
I think it's because IE does not support SVG currently. We can try another browser in the preview window (the right window), for example, webkit-based browser.

I'll try https://github.com/cefsharp/CefSharp first. If it works, users just cannot view the exported html in IE browser, but it shows the graph in the preview window, which is acceptable from my view.

**Comment by mike-ward** [comment]
IE supports SVG. I talked with the author of Mermaid and he's
investigating.

**Comment by mike-ward** [comment]
Issues still not resolved in mermaid. Dropping it.
