### ISSUE TITLE
Line ending option does not work

### ISSUE THREAD

**Issue by seperman** [mike-ward/Markdown-Edit#90]
I just changed the line ending in the user_settings.json to `"LineEnding": "n",` but it is still saving in windows line ending.

**Comment by mike-ward** [comment]
Just tried this and it's working here (I checked by opening the saved file with a binary editor).

**Comment by seperman** [comment]
I actually downgraded to an older version of Markdown edit due to this issue because git kept thinking I have deleted all lines and re-added them which was very annoying. I will post here more info when I install the latest version again.
