### ISSUE TITLE
Alt+Ctrl shortcut prevents typing [

### ISSUE THREAD

**Issue by molnarm** [mike-ward/Markdown-Edit#92]
There is a shortcut in the list which has Alt+Ctrl modifiers (Alt+Ctrl+F = Wrap, Format, Use Reference Links), despite [being not recommended](https://en.wikipedia.org/wiki/AltGr_key#Control_.2B_Alt_as_a_substitute), since it potentially breaks character input with layouts which use AltGr to enter characters (for example, in Hungarian, AltGr+F is [, but whenever I try to type it, the document is reformatted instead).

Making keyboard shortcuts configurable might be too big of a change, so as a start, this shortcut could become optional in settings.

**Comment by mike-ward** [comment]
Thanks for the bug report. I'll change the shortcut so it does not collide with character input.
