### ISSUE TITLE
Saving snippets file

### ISSUE THREAD

**Issue by Li-An** [mike-ward/Markdown-Edit#93]
Hello,
with last version, saving snippet text file does not more kill Markdown Edit application. But I've got an error message saying that the process cannot access to the file because it's used by another process. So I have to close Markdown Edit to save the text file.

**Comment by mike-ward** [comment]
I can't reproduce this. Frankly, it doesn't make sense to me since all the file operations in MDE are open/close. It doesn't leave files open.

Are you using MDE to edit the snippets file?

**Comment by Li-An** [comment]
I open MarkEdit, F6 to open the snippet txt file, and I make the changes in Notepad.

**Comment by Li-An** [comment]
I suppose it's the "same problem" I had before (Markdown Edit was freezed when I tried to save snippets) in a different way. I cannot guess where it could come from.

**Comment by cyotek** [comment]
I don't suppose it's something as simple as a virus scanner scanning a changed file and MDE trying to read it as the same time? I suppose if you *really* wanted to pin it down, you could use [Process Monitor](https://technet.microsoft.com/en-gb/sysinternals/bb896645) and stick a filter to watch only the changes to the MDE config files and see who's trying to open it.

**Comment by Li-An** [comment]
I desactivaded virus scanner and same problem. I will take a look at Process Monitor.

**Comment by mike-ward** [comment]
Again, I can't imagine how MDE could lock a file you're editing with Notepad. There's something unique about your situation we have yet to discover.

**Comment by Li-An** [comment]
OK, it seems there is a problem with my Wacom graphic tablet - I don't use it at the moment.

https://framapic.org/5Dv18J6XqF4g/qC73ANI0vIQT.png

**Comment by mike-ward** [comment]
Thanks for running this down.
