### ISSUE TITLE
Add a panel featuring the structure of the document

### ISSUE THREAD

**Issue by dubeg** [mike-ward/Markdown-Edit#95]
This is a suggestion, but I'd like to know your opinion on this. This is something that I rarely see in editors, but a panel displaying the outline/structure of the document would be nice. Maybe it could exist as a column to the left of the editor pane, with minimal styles applied. A click on a title would lead to the relevant section in the editor/viewer. Its visibility would be toggle-able, if we want more space for the editor and viewer.

**Comment by mike-ward** [comment]
I've had a couple of requests for this. Low priority at the moment but likely.

**Comment by borekb** [comment]
When I click on a title in the document outline, should it take me to the respective location, as suggested in the OP? The list seems interactive but it doesn't do anything for me. Tried both mouse and Enter.

**Comment by mike-ward** [comment]
It should indeed which it does for me here. Don't know what the issue could be.

**Comment by borekb** [comment]
Oh sorry it does jump, I was just slightly confused by the UI. After selecting the heading and pressing `Esc` to hide the outline, I was looking for a cursor blinking at the right location which doesn't happen for me. But when I press right arrow, left arrow and right arrow again, all is fine. (Maybe some other key sequence would work as well.)

**Comment by mike-ward** [comment]
I'll look into the cursor thing. Sounds like an activation problem.
