### ISSUE TITLE
Insert and paste images as embedded image (data: uri)

### ISSUE THREAD

**Issue by avonwyss** [mike-ward/Markdown-Edit#96]
In order to make self-contained markdown snippets for my application, I usually embed small images (mostly PNG and SVG icons or logos) as data URI:
https://en.wikipedia.org/wiki/Data_URI_scheme

This could also safely be used as default method when pasting images, as it does not cause any privacy issue since the image remains completely embedded in the text. (Still I agree with the comment from @borekb in issue #73 that text should be preferred over images when both are on the clipboard).

Optionally, MDE could warn when the image is over a certain size, since this can considerably blow up the source (maybe at 32kb - which is also the limit that IE8 supports for data URI).

Note: it is a know issue that some sites such as GitHub currently don't display these images.

**Comment by mike-ward** [comment]
v1.22
