### ISSUE TITLE
Allow only one instance of a file

### ISSUE THREAD

**Issue by mica** [mike-ward/Markdown-Edit#97]
If a file is already open, activate the window, don't create a new one.

**Comment by mike-ward** [comment]
How do others feel about this?

**Comment by cyotek** [comment]
Not that it helps, but I'm ambivalent either way.

**Comment by mike-ward** [comment]
Doesn't seem to be much interest in this one.

**Comment by mica** [comment]
But this is just kind of the basic expected behavior of any app. Lack of commentary here doesn't mean it's not worth implementing.

**Comment by mike-ward** [comment]
Notepad doesn't work that way.

**Comment by mica** [comment]
True, but that's the only example I can think of, and it's mainly because it's a 30 year old app.

**Comment by mike-ward** [comment]
Which apps behave this way?

**Comment by mica** [comment]
Just a quick survey of some apps I have here:
- MS Office
- Anything Adobe (e.g. Photoshop, Illustrator)
- Sublime Text
- PowerShell ISE
- Ableton Live
- Cinema 4D

**Comment by mike-ward** [comment]
With the exception of Sublime Text, none of these are text editors.

They're also "heavy" programs (Sublime Text excluded) that take a while to startup.

Most of these programs also lock the files their editing.

In other words, they're the opposite of MDE. MDE is light, minimal and single purpose.

I can see the utility in what you're asking but it requires interacting with system services at program start up time. MDE is quick to start (especially for a WPF program). That's no accident. I worked hard to make sure that first screen arrives quickly.

Checking if MDE is running elsewhere and is editing the file you clicked slows start-up (I've done this in other programs so I have some experience here). So while it may be a useful feature, the downsides (IMO) out-weigh the benefits.

**Comment by mike-ward** [comment]
OK, I looked into this further. It's about a 100 ms hit to check running instances. Less if there are no other instances running. That's acceptable. However, I don't have a way to interrogate the other  process to see what file is has open. Thoughts on this anyone?

**Comment by mike-ward** [comment]
I have something working. I ended up going old school (very old school) and sending old fashioned window messages to interrogate the other MDE processes. I'll have to "live" with this for a while to shake out any bugs/crashes before releasing it. Whenever I have to dip down into allocating memory blocks and marshalling I get nervous about stability.

I doubt this will work with multiple (virtual) desktops due to the nature of window broadcast messages.

**Comment by mica** [comment]
Thanks for sorting this out, Mike. Future would-be accidental-multiple-instance-opening-people will be grateful.
